/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 22 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Matrix.IsDiag.neg SubtractionMonoid => NegZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt Pi.colex_le_iff_of_unique Unique => Inhabited by rfl, simp, aesop, exact?
#fh_home_attempt Pi.lex_le_iff_of_unique Unique => Inhabited by rfl, simp, aesop, exact?
#fh_home_attempt AddCommGroup.add_modEq_right AddCancelCommMonoid => AddCommMonoid by rfl, simp, aesop, exact?
#fh_home_attempt QuaternionAlgebra.re_natCast AddCommGroupWithOne => NatCast by rfl, simp, aesop, exact?
#fh_home_attempt AddMonoid.End.zero_apply AddCommMonoid => AddZero by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.bot_eq_zero AddCommMonoid => Zero by rfl, simp, aesop, exact?
#fh_home_attempt QuadraticAlgebra.re_natCast AddCommMonoidWithOne => NatCast by rfl, simp, aesop, exact?
#fh_home_attempt add_add_add_comm' AddCommSemigroup => Add by rfl, simp, aesop, exact?
#fh_home_attempt AddSubmonoid.addOrderOf_le_card AddGroup => AddLeftCancelMonoid by rfl, simp, aesop, exact?
#fh_home_attempt QuaternionAlgebra.im_sub AddGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?
#fh_home_attempt FreeAddMonoid.hom_eq AddMonoid => AddZero by rfl, simp, aesop, exact?
#fh_home_attempt Function.Periodic.add_period AddSemigroup => Add by rfl, simp, aesop, exact?
#fh_home_attempt Multiset.addHom_ext AddZeroClass => AddZero by rfl, simp, aesop, exact?
#fh_home_attempt compl_le_hnot BiheytingAlgebra => CoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Set.mem_compl_image BooleanAlgebra => Compl by rfl, simp, aesop, exact?
#fh_home_attempt Disjoint.le_symmDiff_sup_symmDiff_left BooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt ofBoolRing_neg BooleanAlgebra => Neg by rfl, simp, aesop, exact?
#fh_home_attempt not_isMulTorsionFree_iff_isOfFinOrder CommGroup => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Associates.FactorSet.coe_add CommMonoidWithZero => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.intCast_add CommRing => AddGroupWithOne by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.neg_congr CommRing => Neg by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Int.smul_eq_mul CommRing => NonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.sub_congr CommRing => Sub by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.sub_pf CommRing => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt QuaternionAlgebra.eq_re_of_eq_coe CommRing => Zero by rfl, simp, aesop, exact?
#fh_home_attempt IsSelfAdjoint.mul CommSemigroup => CommMagma by rfl, simp, aesop, exact?
#fh_home_attempt mul_mul_mul_comm' CommSemigroup => Mul by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.add_congr CommSemiring => Add by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.add_pf_add_lt CommSemiring => AddSemigroup by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.mul_pow CommSemiring => CommMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.add_mul CommSemiring => Distrib by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.pow_nat CommSemiring => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Nat.smul_eq_mul CommSemiring => NonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt iSup_symmDiff_iSup_le CompleteBooleanAlgebra => CompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt CompleteSublattice.subtype_apply CompleteLattice => Lattice by rfl, simp, aesop, exact?
#fh_home_attempt Finset.untrop_sum ConditionallyCompleteLinearOrder => LinearOrder by rfl, simp, aesop, exact?
#fh_home_attempt IsLeast.directedOn ConditionallyCompletePartialOrderInf => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsGreatest.directedOn ConditionallyCompletePartialOrderSup => LE by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.evalEval_smul DistribSMul => SMulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.FieldSimp.eq_div_of_eq_one_of_subst' DivInvOneMonoid => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Function.HasFiniteMulSupport.inv DivisionMonoid => InvOneClass by rfl, simp, aesop, exact?
#fh_home_attempt Finset.isUnit_coe DivisionMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt DualNumber.isNilpotent_iff_eps_dvd DivisionSemiring => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt UniqueDiffWithinAt.pi DivisionSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt edist_pos EMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt MonomialOrder.isUnit_leadingCoeff Field => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.CancelDenoms.div_subst Field => DivisionCommMonoid by rfl, simp, aesop, exact?
#fh_home_attempt QuadraticAlgebra.re_nnratCast Field => NNRatCast by rfl, simp, aesop, exact?
#fh_home_attempt QuadraticAlgebra.re_ratCast Field => RatCast by rfl, simp, aesop, exact?
#fh_home_attempt Filter.cofinite_eq_bot Finite => Bot by rfl, simp, aesop, exact?
#fh_home_attempt Fintype.toOrderBot.congr_simp Fintype => LE by rfl, simp, aesop, exact?
#fh_home_attempt Booleanisation.lift_bot GeneralizedBooleanAlgebra => Bot by rfl, simp, aesop, exact?
#fh_home_attempt Disjoint.symmDiff_left GeneralizedBooleanAlgebra => DistribLattice by rfl, simp, aesop, exact?
#fh_home_attempt Booleanisation.not_comp_le_lift GeneralizedBooleanAlgebra => LE by rfl, simp, aesop, exact?
#fh_home_attempt Booleanisation.not_comp_lt_lift GeneralizedBooleanAlgebra => LT by rfl, simp, aesop, exact?
#fh_home_attempt Booleanisation.lift_sup_lift GeneralizedBooleanAlgebra => Max by rfl, simp, aesop, exact?
#fh_home_attempt Booleanisation.lift_inf_lift GeneralizedBooleanAlgebra => Min by rfl, simp, aesop, exact?
#fh_home_attempt Submonoid.orderOf_le_card Group => LeftCancelMonoid by rfl, simp, aesop, exact?
#fh_home_attempt orderOf_eq_zero_iff_eq_zero GroupWithZero => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt gcd_dvd_iff_exists IsBezout => GCDMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Associates.FactorSet.prod_eq_zero_iff IsCancelMulZero => NoZeroDivisors by rfl, simp, aesop, exact?
#fh_home_attempt Nat.zero_le_self_sub_floor IsStrictOrderedRing => AddRightMono by rfl, simp, aesop, exact?
#fh_home_attempt UniformSpace.Completion.coe_mul IsTopologicalRing => ContinuousMul by rfl, simp, aesop, exact?
#fh_home_attempt Lean.Grind.CommRing.Poly.normEq0_eq Lean.Grind.CommRing => Lean.Grind.Ring by rfl, simp, aesop, exact?
#fh_home_attempt Lean.Order.chain_conj Lean.Order.CCPO => Lean.Order.PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt ProbabilityTheory.withDensity_preCDF MeasureTheory.IsFiniteMeasure => MeasureTheory.SigmaFinite by rfl, simp, aesop, exact?
#fh_home_attempt Metric.lipschitz_infDist_set MetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt ReaderT.run_seq Monad => Seq by rfl, simp, aesop, exact?
#fh_home_attempt ReaderT.run_seqLeft Monad => SeqLeft by rfl, simp, aesop, exact?
#fh_home_attempt ReaderT.run_seqRight Monad => SeqRight by rfl, simp, aesop, exact?
#fh_home_attempt FreeMonoid.hom_eq Monoid => MulOne by rfl, simp, aesop, exact?
#fh_home_attempt Finset.noncommProd_mul_distrib_aux Monoid => Semigroup by rfl, simp, aesop, exact?
#fh_home_attempt FiniteMultiplicity.ne_zero MonoidWithZero => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Decidable.mul_lt_mul'' MonoidWithZero => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt MulEquiv.coe_monoidHom_refl MulOneClass => MulOne by rfl, simp, aesop, exact?
#fh_home_attempt CStarMatrix.uniformEmbedding_ofMatrix NonUnitalCStarAlgebra => UniformSpace by rfl, simp, aesop, exact?
#fh_home_attempt noZeroDivisors_tfae NonUnitalNonAssocRing => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt AddMonoidHom.mulLeft₃_eq_mulRight₃ NonUnitalSemiring => NonUnitalNonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.degree_gcd_le_left NormalizedGCDMonoid => GCDMonoid by rfl, simp, aesop, exact?
