/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 13 of 20 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt TopologicalSpace.NonemptyCompacts.isometry_toCompacts EMetricSpace => PseudoMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.NonemptyCompacts.lipschitz_sup EMetricSpace => PseudoMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt OnePoint.equivProjectivization_smul Field => IsField by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_nnratCast Field => IsField by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_ratCast Field => IsField by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subfield.algebraMap_ofSubfield Field => IsField by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Jacobian.Point.add_point Field => IsField by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Jacobian.Point.neg_point Field => IsField by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Projective.Point.add_point Field => IsField by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Projective.Point.neg_point Field => IsField by rfl, simp, aesop, exact?, grind
#fh_home_attempt OnePoint.equivProjectivization_smul Field => Semifield by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_nnratCast Field => Semifield by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_ratCast Field => Semifield by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subfield.algebraMap_ofSubfield Field => Semifield by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Jacobian.Point.add_point Field => Semifield by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Jacobian.Point.neg_point Field => Semifield by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Projective.Point.add_point Field => Semifield by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Projective.Point.neg_point Field => Semifield by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.bihimp_def Fintype => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.compl_inter Fintype => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.compl_ssubset_compl Fintype => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.compl_subset_compl Fintype => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.himp_def Fintype => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.isCoatom_compl_singleton Fintype => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.mem_himp_iff Fintype => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.sdiff_eq_inter_compl Fintype => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.bihimp_def Fintype => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.compl_inter Fintype => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.compl_ssubset_compl Fintype => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.compl_subset_compl Fintype => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.himp_def Fintype => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.isCoatom_compl_singleton Fintype => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.mem_himp_iff Fintype => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.sdiff_eq_inter_compl Fintype => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.compl_union Fintype => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.inter_compl Fintype => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.piecewise_compl Fintype => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.subset_compl_comm Fintype => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.subset_compl_iff_disjoint_left Fintype => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.subset_compl_iff_disjoint_right Fintype => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Fintype.toOrderBot.congr_simp Fintype => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Set.Finite.toFinset_compl Fintype => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.comp_sdiff_comp GeneralizedBooleanAlgebra => BooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_bot GeneralizedBooleanAlgebra => BooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_inf_lift GeneralizedBooleanAlgebra => BooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_sdiff_lift GeneralizedBooleanAlgebra => BooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_sup_lift GeneralizedBooleanAlgebra => BooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_le_lift GeneralizedBooleanAlgebra => BooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_lt_lift GeneralizedBooleanAlgebra => BooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Disjoint.symmDiff_left GeneralizedBooleanAlgebra => BooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.comp_sdiff_comp GeneralizedBooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_bot GeneralizedBooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_inf_lift GeneralizedBooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_sdiff_lift GeneralizedBooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_sup_lift GeneralizedBooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_le_lift GeneralizedBooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_lt_lift GeneralizedBooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Disjoint.symmDiff_left GeneralizedBooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_bihimp_sup GeneralizedHeytingAlgebra => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_eq_top GeneralizedHeytingAlgebra => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_himp_eq_inf GeneralizedHeytingAlgebra => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_inf_sup GeneralizedHeytingAlgebra => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_triangle GeneralizedHeytingAlgebra => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt himp_bihimp_eq_inf GeneralizedHeytingAlgebra => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt sup_bihimp_bihimp GeneralizedHeytingAlgebra => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt sup_inf_bihimp GeneralizedHeytingAlgebra => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_bihimp_sup GeneralizedHeytingAlgebra => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_eq_top GeneralizedHeytingAlgebra => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_himp_eq_inf GeneralizedHeytingAlgebra => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_inf_sup GeneralizedHeytingAlgebra => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_triangle GeneralizedHeytingAlgebra => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt himp_bihimp_eq_inf GeneralizedHeytingAlgebra => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt sup_bihimp_bihimp GeneralizedHeytingAlgebra => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt sup_inf_bihimp GeneralizedHeytingAlgebra => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_bihimp_sup GeneralizedHeytingAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_eq_top GeneralizedHeytingAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_himp_eq_inf GeneralizedHeytingAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_inf_sup GeneralizedHeytingAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_triangle GeneralizedHeytingAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt himp_bihimp_eq_inf GeneralizedHeytingAlgebra => Units by rfl, simp, aesop, exact?, grind
