/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 11 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt IsMaxOn.iSup_eq ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.hittingAfter_anti ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.hittingAfter_le_of_mem ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.hittingAfter_mono ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.hittingBtwn_anti ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.hittingBtwn_eq_hittingBtwn_of_exists ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.hittingBtwn_le_of_mem ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.hittingBtwn_mono_left ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.le_hittingBtwn ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.notMem_of_lt_hittingAfter ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt csInf_eq_bot_of_bot_mem ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt csInf_lt_iff ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt essInf_eq_sSup ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt essSup_eq_sInf ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt exists_lt_of_lt_csSup ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt lt_csSup_iff ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt trop_sInf_image ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt untrop_sum_eq_sInf_image ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Finset.inf_sdiff_left BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.inf_sdiff_right BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_assoc BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_eq_inf BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_eq_left BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_eq_right BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_himp_left BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_himp_right BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_le_iff_left BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_le_iff_right BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_left_injective BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_left_surjective BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_right_injective BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_right_surjective BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt codisjoint_bihimp_sup BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt codisjoint_himp_self_left BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt codisjoint_himp_self_right BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt himp_bihimp_left BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt himp_bihimp_right BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt inf_himp_bihimp BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt DividedPowers.exp_add' CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt LaurentPolynomial.C_eq_algebraMap CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt LaurentPolynomial.algebraMap_X_pow CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt LaurentPolynomial.algebraMap_eq_toLaurent CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt LaurentSeries.coe_algebraMap CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.natCast_mul CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt MvPowerSeries.c_eq_algebraMap CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Nat.castChoose_eq CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.C_eq_algebraMap CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.Monic.leadingCoeff_notMem CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.Monic.natDegree_pos CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.algebraMap_eq CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.algebraMap_pi_self_eq_eval CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.coe_algebraMap_eq_CC CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.eq_zero_of_mul_eq_zero_of_smul CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt PowerSeries.C_eq_algebraMap CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt PowerSeries.algebraMap_eq CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt PowerSeries.trunc_coe_eq_self CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt QuadraticAlgebra.C_pow CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Submodule.smul_le_span CommSemiring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.GradedObject.categoryOfGradedObjects_comp CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.GradedObject.categoryOfGradedObjects_id CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.GradedObject.eqToHom_apply CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.GradedObject.eqToHom_proj CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.ObjectProperty.ne_bot_iff_exists CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.ObjectProperty.op_inf CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.ObjectProperty.op_sup CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.ObjectProperty.prop_iSup_iff CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.ObjectProperty.prop_inf_iff CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.ObjectProperty.prop_sup_iff CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.ObjectProperty.unop_inf CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.ObjectProperty.unop_sup CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.effectiveEpiFamilyStructCompIso_aux CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.eq_whisker CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.heq_comp CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.isCardinalFiltered_iff_aux₁ CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.whisker_eq CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Monoidal.eval_comp CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Reassoc.eq_whisker' CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?
#fh_home_attempt CommRing.Pic.subsingleton_iff CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt LinearRecurrence.solSpace_rank CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt MvPolynomial.dvd_X_mul_iff CommRing => CommSemiring by rfl, simp, aesop, exact?
