/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 16 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt mul_self_lt_mul_self_iff Semiring => MonoidWithZero by rfl, simp, aesop, exact?
#fh_home_attempt nonneg_le_nonneg_of_sq_le_sq Semiring => MonoidWithZero by rfl, simp, aesop, exact?
#fh_home_attempt Finset.bihimp_def Fintype => BooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.compl_inter Fintype => BooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.compl_ssubset_compl Fintype => BooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.compl_subset_compl Fintype => BooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.himp_def Fintype => BooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.isCoatom_compl_singleton Fintype => BooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.mem_himp_iff Fintype => BooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.sdiff_eq_inter_compl Fintype => BooleanAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_bihimp_sup GeneralizedHeytingAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_eq_top GeneralizedHeytingAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_himp_eq_inf GeneralizedHeytingAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_inf_sup GeneralizedHeytingAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt bihimp_triangle GeneralizedHeytingAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt himp_bihimp_eq_inf GeneralizedHeytingAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt sup_bihimp_bihimp GeneralizedHeytingAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt sup_inf_bihimp GeneralizedHeytingAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt ExponentExists.isTorsion Group => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Filter.isUnit_iff_singleton Group => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Finset.isUnit_iff_singleton Group => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Finset.isUnit_iff_singleton_aux Group => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt IsTorsion.exponentExists Group => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Monoid.minOrder_eq_top Group => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Set.isUnit_iff_singleton Group => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt orderOf_dvd_natCard Group => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.dist_op PseudoMetricSpace => Dist by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.dist_unop PseudoMetricSpace => Dist by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.dist_op PseudoMetricSpace => Dist by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.dist_unop PseudoMetricSpace => Dist by rfl, simp, aesop, exact?
#fh_home_attempt Subtype.dist_eq PseudoMetricSpace => Dist by rfl, simp, aesop, exact?
#fh_home_attempt ULift.dist_eq PseudoMetricSpace => Dist by rfl, simp, aesop, exact?
#fh_home_attempt ULift.dist_up_up PseudoMetricSpace => Dist by rfl, simp, aesop, exact?
#fh_home_attempt dist_triangle_max PseudoMetricSpace => Dist by rfl, simp, aesop, exact?
#fh_home_attempt Finset.Nonempty.zsmul SubtractionMonoid => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Finset.neg_subset_sub_right SubtractionMonoid => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Finset.zsmul_empty SubtractionMonoid => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Finset.zsmul_singleton SubtractionMonoid => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Abel.unfold_sub SubtractionMonoid => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Set.neg_subset_sub_right SubtractionMonoid => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Set.univ_sub_univ SubtractionMonoid => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Set.zsmul_empty SubtractionMonoid => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt QuaternionAlgebra.imI_sub AddGroup => Sub by rfl, simp, aesop, exact?
#fh_home_attempt QuaternionAlgebra.imJ_sub AddGroup => Sub by rfl, simp, aesop, exact?
#fh_home_attempt QuaternionAlgebra.imK_sub AddGroup => Sub by rfl, simp, aesop, exact?
#fh_home_attempt QuaternionAlgebra.mk_sub_mk AddGroup => Sub by rfl, simp, aesop, exact?
#fh_home_attempt QuaternionAlgebra.re_sub AddGroup => Sub by rfl, simp, aesop, exact?
#fh_home_attempt WithConv.ofConv_sub AddGroup => Sub by rfl, simp, aesop, exact?
#fh_home_attempt WithConv.toConv_sub AddGroup => Sub by rfl, simp, aesop, exact?
#fh_home_attempt AddAut.vadd_def AddMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt Finset.noncommSum_lemma AddMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt WithConv.ofConv_add AddMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt WithConv.toConv_add AddMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt isAddRegular_toAdd AddMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt isRegular_ofAdd AddMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt min_add_distrib AddMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt SkewMonoidAlgebra.coeff_injective AddMonoid => Zero by rfl, simp, aesop, exact?
#fh_home_attempt SkewMonoidAlgebra.coeff_ofCoeff AddMonoid => Zero by rfl, simp, aesop, exact?
#fh_home_attempt SkewMonoidAlgebra.coeff_zero AddMonoid => Zero by rfl, simp, aesop, exact?
#fh_home_attempt SkewMonoidAlgebra.eta AddMonoid => Zero by rfl, simp, aesop, exact?
#fh_home_attempt SkewMonoidAlgebra.ext_iff AddMonoid => Zero by rfl, simp, aesop, exact?
#fh_home_attempt SkewMonoidAlgebra.ofCoeff_zero AddMonoid => Zero by rfl, simp, aesop, exact?
#fh_home_attempt SkewMonoidAlgebra.toFinsupp_apply AddMonoid => Zero by rfl, simp, aesop, exact?
#fh_home_attempt ArchimedeanClass.exists_nat_ge_of_mk_nonneg IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?
#fh_home_attempt ArchimedeanClass.isAddRegular_mk IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?
#fh_home_attempt NNRat.cast_nonneg IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?
#fh_home_attempt Nat.cast_div_le IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?
#fh_home_attempt Nat.inv_pos_of_nat IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?
#fh_home_attempt Nat.one_div_cast_pos IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?
#fh_home_attempt abs_pow_eq_one IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Meta.Positivity.max_ne LinearOrder => Max by rfl, simp, aesop, exact?
#fh_home_attempt Tropical.trop_max_def LinearOrder => Max by rfl, simp, aesop, exact?
#fh_home_attempt Tropical.trop_sup_def LinearOrder => Max by rfl, simp, aesop, exact?
#fh_home_attempt Tropical.untrop_max LinearOrder => Max by rfl, simp, aesop, exact?
#fh_home_attempt Tropical.untrop_sup LinearOrder => Max by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.coe_max LinearOrder => Max by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.coe_max LinearOrder => Max by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithLawson.isClosed_preimage_ofLawson Preorder => TopologicalSpace by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithLawson.isOpen_def Preorder => TopologicalSpace by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithLawson.isOpen_preimage_ofLawson Preorder => TopologicalSpace by rfl, simp, aesop, exact?
