/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 4 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt NonemptyInterval.fst_pow Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.fst_zero Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.snd_div Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.snd_natCast Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.snd_nsmul Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.snd_one Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.snd_pow Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.snd_zero Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.toProd_nsmul Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.toProd_one Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.toProd_pow Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.toProd_zero Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Nonneg.coe_add Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Nonneg.coe_nsmul Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Nonneg.coe_zero Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Nonneg.mk_eq_zero Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Ordnode.insert'_eq_insertWith Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Ordnode.insert_eq_insertWith Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Right.nsmul_nonneg Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Right.one_le_pow_of_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Set.Finite.bddAbove_biUnion Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Set.not_isMax_coe Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Set.not_isMin_coe Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithLower.ofLower_le_ofLower Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithLower.toLower_le_toLower Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithLowerSet.ofLowerSet_le_iff Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithLowerSet.toLowerSet_le_iff Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithUpper.ofUpper_le_ofUpper Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithUpper.toUpper_le_toUpper Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithUpperSet.ofUpperSet_le_iff Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithUpperSet.toUpperSet_le_iff Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.lawson_le_lower Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.lawson_le_scott Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.scottHausdorff_le_scott Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Topology.upperSet_le_scott Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Units.val_le_val Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.eq_bot_iff_forall_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.le_coe_unbotD Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.coe_iSup Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.coe_untopD_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.eq_top_iff_forall_ge Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.exp_le_exp Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.le_coe_unzeroD Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.le_exp_of_log_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.log_le_log Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt bddAbove_insert Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt bot_mem_lowerBounds Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt div_self_le_one Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt exists_nonneg_add_of_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt exists_one_le_mul_of_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt inv_mul_le_one Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt inv_mul_left_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt inv_mul_right_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt isCofinalFor_or_isCofinalFor_of_directedOn_union Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt isGLB_congr Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt isGreatest_univ_iff Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt isLUB_congr Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt isMax_top Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt isMin_bot Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt le_iff_exists_add' Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt le_iff_exists_mul' Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt le_inv_mul_left Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt le_inv_mul_right Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt le_mul_inv_left Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt le_mul_inv_right Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt mul_inv_left_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt mul_inv_right_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt nsmul_le_nsmul_add_of_sq_le_add Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt nsmul_le_nsmul_right Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt pow_le_pow_left' Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt pow_le_pow_mul_of_sq_le_mul Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt top_mem_upperBounds Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Filter.Tendsto.atTop_zsmul_const LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt Filter.tendsto_const_mul_pow_atBot_iff LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt Filter.tendsto_div_const_atBot_of_neg LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt Filter.tendsto_div_const_atBot_of_pos LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt Filter.tendsto_div_const_atTop_of_neg LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt Filter.tendsto_zpow_atTop_atTop LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt Finset.sortedGT_sort LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt Finset.sortedLT_sort LinearOrder => PartialOrder by rfl, simp, aesop, exact?
