/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 4 of 6 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Pi.apply_le_of_toLex LinearOrder => PartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nucleus.sInf_apply CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_insert CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_pair CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_union CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_insert CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_pair CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_union CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nucleus.sInf_apply CompleteLattice => Lattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_insert CompleteLattice => Lattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_pair CompleteLattice => Lattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_union CompleteLattice => Lattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_insert CompleteLattice => Lattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_pair CompleteLattice => Lattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_union CompleteLattice => Lattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt IsUnit.neg HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt SemiconjBy.neg_one_left HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt SemiconjBy.neg_one_right HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt Units.coe_neg_one HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt Units.val_neg HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt neg_one_pow_eq_or HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddAut.vadd_def AddMonoid => AddZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt SkewMonoidAlgebra.coeff_zero AddMonoid => AddZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt SkewMonoidAlgebra.ofCoeff_zero AddMonoid => AddZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_add AddMonoid => AddZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_add AddMonoid => AddZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddAut.vadd_def AddMonoid => AddZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt SkewMonoidAlgebra.coeff_zero AddMonoid => AddZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt SkewMonoidAlgebra.ofCoeff_zero AddMonoid => AddZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_add AddMonoid => AddZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_add AddMonoid => AddZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.op_nsmul AddMonoid => NSMul by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.unop_nsmul AddMonoid => NSMul by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_nsmul AddMonoid => NSMul by rfl, simp, aesop, exact?, grind
#fh_home_attempt mul_nsmul AddMonoid => NSMul by rfl, simp, aesop, exact?, grind
#fh_home_attempt nsmul_iterate AddMonoid => NSMul by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddMonoid.End.zero_apply AddCommMonoid => AddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.bot_eq_zero AddCommMonoid => AddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ofDegLex_add AddCommMonoid => AddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt toDegLex_add AddCommMonoid => AddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Jacobian.Point.add_point Field => EuclideanDomain by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Jacobian.Point.neg_point Field => EuclideanDomain by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Projective.Point.add_point Field => EuclideanDomain by rfl, simp, aesop, exact?, grind
#fh_home_attempt WeierstrassCurve.Projective.Point.neg_point Field => EuclideanDomain by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_inf_lift GeneralizedBooleanAlgebra => DistribLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_sup_lift GeneralizedBooleanAlgebra => DistribLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_le_lift GeneralizedBooleanAlgebra => DistribLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_lt_lift GeneralizedBooleanAlgebra => DistribLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_neg AddCommGroup => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_neg AddCommGroup => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_neg AddCommGroup => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_neg AddCommGroup => NegZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_neg AddCommGroup => NegZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_neg AddCommGroup => NegZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_sub AddCommGroup => SubNegMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_sub AddCommGroup => SubNegMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_sub AddCommGroup => SubNegMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_sub AddCommGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_sub AddCommGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_sub AddCommGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_intCast AddCommGroupWithOne => AddGroupWithOne by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.re_intCast AddCommGroupWithOne => AddGroupWithOne by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.re_natCast AddCommGroupWithOne => AddGroupWithOne by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddAut.vadd_def AddMonoid => AddSemigroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_add AddMonoid => AddSemigroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_add AddMonoid => AddSemigroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt CategoryTheory.GradedObject.hom_ext CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?, grind
#fh_home_attempt CategoryTheory.WithInitial.false_of_to_star CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?, grind
#fh_home_attempt CategoryTheory.WithTerminal.false_of_from_star CategoryTheory.Category => CategoryTheory.CategoryStruct by rfl, simp, aesop, exact?, grind
#fh_home_attempt ConjAct.ofConjAct_zero GroupWithZero => DivInvOneMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ConjAct.toConjAct_zero GroupWithZero => DivInvOneMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt orderOf_eq_zero_iff_eq_zero GroupWithZero => DivInvOneMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ConjAct.ofConjAct_zero GroupWithZero => DivisionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ConjAct.toConjAct_zero GroupWithZero => DivisionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt orderOf_eq_zero_iff_eq_zero GroupWithZero => DivisionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArchimedeanClass.mk_mul IsStrictOrderedRing => IsOrderedCancelAddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArchimedeanClass.mk_one IsStrictOrderedRing => IsOrderedCancelAddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArchimedeanClass.mk_pow IsStrictOrderedRing => IsOrderedCancelAddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_nnqsmul Semifield => CommSemiring by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_zpow Semifield => CommSemiring by rfl, simp, aesop, exact?, grind
