/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 6 of 13 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 400000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Mathlib.Meta.NormNum.isNNRat_abs_nonneg LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.isBounded_of_abs_le LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.isBounded_of_abs_lt LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Multiset.abs_sum_le_sum_abs LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.inv_uIcc LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.neg_uIcc LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_add' LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_add_three LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_le LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_le_abs_of_nonpos LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_one LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_sub LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_sub_abs_le_abs_sub LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_sub_le LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt add_abs_nonneg LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_div LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_div_le LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_div_mabs_le_mabs_div LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_le LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_le_mabs_of_le_one LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_le_max_mabs_mabs LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_mul' LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_mul_three LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt one_le_mul_mabs LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sq_eq_sq_iff_abs_eq_abs LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.mul_univ_of_one_mem Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.univ_mul_of_one_mem Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsLeftRegular.mul_eq_one_symm Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.Sublist.prod_le_prod' Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.one_le_prod_of_one_le Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.prod_eq_one Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.prod_take_mul_prod_drop Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MonoidHom.ext_int Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt PresentedMonoid.ext Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt RingCon.coe_listProd Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt RingCon.listProd Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.mulIndicator_apply_le Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.mulIndicator_le Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.mulIndicator_le_self Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.mul_univ_of_one_mem Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.univ_mul_of_one_mem Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Submonoid.closure_mul_le Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Submonoid.mul_subset Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_of_forall_one_lt_le_mul Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mem_own_leftCoset Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mem_own_rightCoset Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_eq_left Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_eq_right Monoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt AddSubmonoid.add_subset AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt AddSubmonoid.closure_add_le AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.add_univ_of_zero_mem AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.univ_add_of_zero_mem AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finsupp.embSigma_add AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.Sublist.sum_le_sum AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.sum_eq_zero AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.sum_nonneg AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt PresentedAddMonoid.ext AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt RingCon.coe_listSum AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt RingCon.listSum AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.add_univ_of_zero_mem AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.univ_add_of_zero_mem AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithBot.lt_zero_iff_eq_bot AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt add_eq_left AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt add_eq_right AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_of_forall_pos_le_add AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mem_own_leftAddCoset AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mem_own_rightAddCoset AddMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Convexity.StdSimplex.support_weights_nonempty PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Convexity.StdSimplex.weights_inj PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Convexity.StdSimplex.weights_ne_zero PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Convexity.StdSimplex.weights_nonneg PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ENat.map_natCast_nonneg PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.eventuallyLE_antisymm_iff PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finsupp.le_iff' PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Int.cast_nonneg PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsStrictlyPositive.of_subsingleton PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.accumulate_bot PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.dissipate_bot PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.indicator_apply_le PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.indicator_le PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
