/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 5 of 20 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt NonemptyInterval.snd_one Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_pow Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_zero Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.toProd_nsmul Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.toProd_one Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.toProd_pow Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.toProd_zero Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_add Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_nsmul Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_zero Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_eq_zero Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Positive.coe_add Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.ofLower_le_ofLower Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.ofLower_lt_ofLower Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.toLower_le_toLower Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.toLower_lt_toLower Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLowerSet.ofLowerSet_le_iff Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLowerSet.toLowerSet_le_iff Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.ofUpper_le_ofUpper Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.ofUpper_lt_ofUpper Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.toUpper_le_toUpper Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.toUpper_lt_toUpper Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpperSet.ofUpperSet_le_iff Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpperSet.toUpperSet_le_iff Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.lawson_le_lower Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.lawson_le_scott Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.scottHausdorff_le_scott Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.upperSet_le_scott Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Units.val_le_val Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Units.val_lt_val Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.op_le_op Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.unop_le_unop Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddUnits.val_le_val Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddUnits.val_lt_val Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.coe_lt_coe Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Interval.bot_div Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Interval.div_bot Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Interval.dual_top Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_le_op Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_le_unop Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.coe_div_interval Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.coe_one_interval Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.coe_top_interval Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.coe_zero_interval Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.dual_top Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_div Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_natCast Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_nsmul Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_one Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_pow Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_zero Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_div Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_natCast Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_nsmul Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_one Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_pow Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_zero Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.toProd_nsmul Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.toProd_one Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.toProd_pow Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.toProd_zero Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_add Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_nsmul Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_zero Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_eq_zero Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Positive.coe_add Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.ofLower_le_ofLower Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.ofLower_lt_ofLower Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.toLower_le_toLower Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.toLower_lt_toLower Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLowerSet.ofLowerSet_le_iff Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLowerSet.toLowerSet_le_iff Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.ofUpper_le_ofUpper Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.ofUpper_lt_ofUpper Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.toUpper_le_toUpper Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.toUpper_lt_toUpper Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpperSet.ofUpperSet_le_iff Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpperSet.toUpperSet_le_iff Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.lawson_le_lower Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.lawson_le_scott Preorder => Vector by rfl, simp, aesop, exact?, grind
