/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 6 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Set.preimage_mul_const_Iic_of_neg LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_mul_const_Iio_of_neg LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_mul_const_Ioi_of_neg LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt Set.subsingleton_Icc_iff LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt Units.inv_pos LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt add_le_mul_of_left_le_right LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt add_le_mul_of_right_le_left LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt antivaryOn_iff_forall_mul_nonpos LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt antivaryOn_iff_mul_rearrangement LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt antivary_iff_forall_mul_nonpos LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt antivary_iff_mul_rearrangement LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt archimedean_iff_nat_lt LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt existsUnique_zpow_near_of_one_lt LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt exists_pow_lt_of_lt_one LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt exists_rat_lt LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt le_of_mul_le_of_one_le LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt monovaryOn_iff_forall_mul_nonneg LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt monovaryOn_iff_mul_rearrangement LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt monovary_iff_forall_mul_nonneg LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt monovary_iff_mul_rearrangement LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt mul_smul_one_lt_iff LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt neg_one_lt_zero LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt pow_div_pow_eventuallyEq_atBot LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt pow_div_pow_eventuallyEq_atTop LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt pow_eq_one_iff_cases LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt pow_eq_pow_iff_cases LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt zpow_eq_one_iff_cases₀ LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt zpow_eq_zpow_iff_cases₀ LinearOrder => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt AddCircle.coe_eq_zero_of_pos_iff LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt DedekindCut.lt_iff_exists LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt DedekindCut.lt_iff_exists' LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Finset.Icc_pred_right_eq_Ico LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Finset.Icc_succ_left_eq_Ioc LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Finset.Ici_succ_eq_Ioi LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Finset.Iic_pred_eq_Iio LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Finset.exists_lt_of_prod_lt' LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.DegLex.single_strictAnti LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.Lex.single_strictAnti LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt IsLowerSet.eq_empty_or_Iic LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt List.exists_le_of_prod_le' LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt List.exists_lt_of_prod_lt' LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt List.sortedGE_insertionSort LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt List.sortedGE_mergeSort LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt List.sortedLE_insertionSort LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt List.sortedLE_mergeSort LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Order.Iic_one LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Order.Iic_two LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Order.Iio_one LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Order.Iio_two LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Order.IsSuccPrelimit.le_iff_forall_le LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Order.aleph0_le_cof LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Order.aleph0_le_cof_iff LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Order.lt_succ_iff_of_not_isMax LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Order.lt_succ_iff_of_not_isMax' LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Order.succ_le_succ_iff LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Order.succ_lt_succ_iff LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Pi.apply_le_of_toColex LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Pi.apply_le_of_toLex LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt PseudoMetric.nonneg LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Icc_pred_right_eq_Ico_of_not_isMin LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Icc_succ_left_eq_Ioc_of_not_isMax LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Ici.isSuccLimit_coe LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Ici_succ_eq_Ioi_of_not_isMax LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Ico_succ_left_eq_Ioo LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Iic_pred_eq_Iio_of_not_isMin LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Ioc_pred_right_eq_Ioo LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.insert_Icc_left_eq_Icc_pred LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.insert_Icc_pred_right_eq_Icc LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.insert_Icc_right_eq_Icc_succ LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.insert_Icc_succ_left_eq_Icc LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.insert_Ico_left_eq_Ico_pred_of_not_isMin LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.insert_Ioc_right_eq_Ioc_succ_of_not_isMax LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt StrictMono.id_le LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt denselyOrdered_set_iff_subsingleton LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt dirSupClosedOn_iff_of_linearOrder LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt dirSupClosed_iff_of_linearOrder LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt dirSupInaccOn_iff_of_linearOrder LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt dirSupInacc_iff_of_linearOrder LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt exists_lub_Iio LinearOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt exists_square_le LinearOrder => Preorder by rfl, simp, aesop, exact?
