/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 12 of 20 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt WithConv.toConv_add AddMonoid => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_nsmul AddMonoid => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt mul_nsmul AddMonoid => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt nsmul_iterate AddMonoid => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddAut.vadd_def AddMonoid => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.op_nsmul AddMonoid => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.unop_nsmul AddMonoid => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt SkewMonoidAlgebra.coeff_zero AddMonoid => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt SkewMonoidAlgebra.ofCoeff_zero AddMonoid => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_add AddMonoid => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_add AddMonoid => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_nsmul AddMonoid => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt mul_nsmul AddMonoid => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt nsmul_iterate AddMonoid => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Codisjoint.bihimp_left BooleanAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Codisjoint.bihimp_right BooleanAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt codisjoint_iff_compl_le_left BooleanAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt codisjoint_iff_compl_le_right BooleanAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_inf BooleanAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_symmDiff_self BooleanAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt symmDiff_compl_self BooleanAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt symmDiff_top BooleanAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt top_sdiff BooleanAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt top_symmDiff BooleanAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Codisjoint.bihimp_left BooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Codisjoint.bihimp_right BooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt codisjoint_iff_compl_le_left BooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt codisjoint_iff_compl_le_right BooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_inf BooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_symmDiff_self BooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt symmDiff_compl_self BooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt symmDiff_top BooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt top_sdiff BooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt top_symmDiff BooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.associated_map_mk CommMonoid => Monoid.IsTorsion by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.decompositionMonoid_iff CommMonoid => Monoid.IsTorsion by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.isPrimal_mk CommMonoid => Monoid.IsTorsion by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_dvd_mk CommMonoid => Monoid.IsTorsion by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_isRelPrime_iff CommMonoid => Monoid.IsTorsion by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_mul_mk CommMonoid => Monoid.IsTorsion by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.HasMulAntidiagonal.mulAntidiagonal.fst_le CommMonoid => Monoid.IsTorsion by rfl, simp, aesop, exact?, grind
#fh_home_attempt emultiplicity_mk_eq_emultiplicity CommMonoid => Monoid.IsTorsion by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.associated_map_mk CommMonoid => Submonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.decompositionMonoid_iff CommMonoid => Submonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.isPrimal_mk CommMonoid => Submonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_dvd_mk CommMonoid => Submonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_isRelPrime_iff CommMonoid => Submonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_mul_mk CommMonoid => Submonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.HasMulAntidiagonal.mulAntidiagonal.fst_le CommMonoid => Submonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt emultiplicity_mk_eq_emultiplicity CommMonoid => Submonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.associated_map_mk CommMonoid => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.decompositionMonoid_iff CommMonoid => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.isPrimal_mk CommMonoid => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_dvd_mk CommMonoid => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_isRelPrime_iff CommMonoid => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_mul_mk CommMonoid => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.HasMulAntidiagonal.mulAntidiagonal.fst_le CommMonoid => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt emultiplicity_mk_eq_emultiplicity CommMonoid => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.associated_map_mk CommMonoid => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.decompositionMonoid_iff CommMonoid => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.isPrimal_mk CommMonoid => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_dvd_mk CommMonoid => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_isRelPrime_iff CommMonoid => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.mk_mul_mk CommMonoid => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.HasMulAntidiagonal.mulAntidiagonal.fst_le CommMonoid => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt emultiplicity_mk_eq_emultiplicity CommMonoid => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.Closeds.edist_eq EMetricSpace => MetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.Closeds.lipschitz_sup EMetricSpace => MetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.Compacts.edist_eq EMetricSpace => MetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.Compacts.isometry_singleton EMetricSpace => MetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.Compacts.lipschitz_sup EMetricSpace => MetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.NonemptyCompacts.isometry_singleton EMetricSpace => MetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.NonemptyCompacts.isometry_toCompacts EMetricSpace => MetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.NonemptyCompacts.lipschitz_sup EMetricSpace => MetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.Closeds.edist_eq EMetricSpace => PseudoMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.Closeds.lipschitz_sup EMetricSpace => PseudoMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.Compacts.edist_eq EMetricSpace => PseudoMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.Compacts.isometry_singleton EMetricSpace => PseudoMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.Compacts.lipschitz_sup EMetricSpace => PseudoMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.NonemptyCompacts.isometry_singleton EMetricSpace => PseudoMetricSpace by rfl, simp, aesop, exact?, grind
