/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 8 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt ofLex_zero Zero => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.op_eq_one_iff One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.op_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.unop_eq_one_iff One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.unop_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt Function.const_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt Function.extend_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.op_eq_one_iff One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.op_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.unop_eq_one_iff One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.unop_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt Pi.comp_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt Pi.one_comp One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt Set.Nonempty.eq_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt Sum.elim_one_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.bot_lt_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.bot_ne_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.coe_eq_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.coe_le_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.coe_lt_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.coe_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.map_eq_one_iff One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.map_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.one_eq_map_iff One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.one_le_coe One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.one_lt_coe One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.one_ne_bot One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.unbotD_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.unbot_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.coe_eq_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.coe_le_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.coe_lt_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.coe_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.map_eq_one_iff One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.map_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.one_eq_map_iff One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.one_le_coe One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.one_lt_coe One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.one_lt_top One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.one_ne_top One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.top_ne_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.untopD_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.untop_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.coe_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.recZeroCoe_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt ofColex_eq_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt ofColex_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt ofDual_eq_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt ofDual_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt ofLex_eq_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt ofLex_one One => OfNat by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.nonneg_op PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.nonneg_unop PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.one_le_op PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.one_le_unop PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.op_le_one PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.op_nonpos PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.unop_le_one PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.unop_nonpos PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Convexity.StdSimplex.support_weights_nonempty PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Convexity.StdSimplex.weights_inj PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Convexity.StdSimplex.weights_ne_zero PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Convexity.StdSimplex.weights_nonneg PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt ENat.map_natCast_nonneg PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Filter.eventuallyLE_antisymm_iff PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finset.Colex.le_def PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finset.Colex.singleton_le_singleton PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finset.Colex.toColex_le_singleton PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finset.Colex.toColex_le_toColex PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finset.Colex.toColex_sdiff_le_toColex_sdiff PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finset.HasAntidiagonal.antidiagonal.fst_le PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finset.HasAntidiagonal.antidiagonal.snd_le PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finset.HasMulAntidiagonal.mulAntidiagonal.fst_le PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finset.HasMulAntidiagonal.mulAntidiagonal.snd_le PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.bot_eq_zero PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.le_iff' PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Int.cast_nonneg PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsStrictlyPositive.of_subsingleton PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Linarith.le_of_eq_of_le PartialOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Linarith.le_of_le_of_eq PartialOrder => LE by rfl, simp, aesop, exact?
