/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 1 of 13 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 400000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt DedekindCut.principal_inj PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.comap_inv_atBot PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.comap_neg_atBot PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.map_inv_atBot PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.map_neg_atBot PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_atTop_add_left_of_le' PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_atTop_add_right_of_le' PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_atTop_mul_left_of_le' PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_atTop_mul_right_of_le' PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_inv_atBot_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_inv_atTop_atBot PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_inv_atTop_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_neg_atBot_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_neg_atTop_atBot PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_neg_atTop_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.Ici_erase PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.Ico_filter_le_left PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.Iic_erase PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.Iio_insert PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.Ioi_insert PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.prod_add_prod_le' PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finsupp.degree_comapDomain_le_of_canonicallyOrderedAdd PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finsupp.le_degree PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Flag.coe_covBy_coe PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsBot.isMin_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsForwardInvariant.isInvariant PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.SortedGT.eq_of_mem_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.Subset.antisymm_of_sortedGT PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.Subset.antisymm_of_sortedLT PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.one_le_prod PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.prod_map_le_prod_map₀ PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.prod_nonneg PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.prod_pos PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.weightedSMul_nonneg PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Multiset.mem_le_prod_of_one_le PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Multiset.prod_map_le_pow_card PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Nat.mono_cast PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.IsPredPrelimit.lt_sub_natCast PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.IsSuccPrelimit.add_natCast_lt PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.krullDim_le_one_iff_forall_isMax PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.krullDim_le_one_iff_forall_isMin PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.krullDim_le_one_iff_of_boundedOrder PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.not_isSuccPrelimit_iff_mem_range_succ PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Right.inv_nonneg PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Right.inv_pos PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Icc_sdiff_left PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Icc_self PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Ico_eq_singleton_left_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Ico_sdiff_left PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Iic_sdiff_right PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Iio_eq_singleton_bot_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Ioi_eq_singleton_top_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.add_mem_Icc_iff_left PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.add_mem_Icc_iff_right PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.indicator_le_self PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.inv_Ici PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.inv_Iic PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.inv_mem_Icc_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.mulIndicator_le_self PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.neg_Ici PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.neg_Iic PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.neg_mem_Icc_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_add_const_Iic PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_add_Ici PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_add_Iic PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_div_Ici PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_div_Iic PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_mul_Ici PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_mul_Iic PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_sub_Ici PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_sub_Iic PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_mul_const_Iic PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.sub_mem_Icc_iff_left PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.sub_mem_Icc_iff_right PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.sub_mem_Ico_zero_iff_right PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.sub_mem_Ioc_zero_iff_right PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.sub_mem_Ioo_zero_iff_right PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt UpperSet.Ioi_eq_top PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithBot.one_le_iff_pos PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithTop.pow_right_strictMono PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
