/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 19 of 20 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt MulOpposite.unop_zpow DivInvMonoid => ZPow by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_nnratCast Field => DivisionRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_ratCast Field => DivisionRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_le_lift GeneralizedBooleanAlgebra => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_lt_lift GeneralizedBooleanAlgebra => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArchimedeanClass.mk_inv IsOrderedRing => IsOrderedCancelAddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArchimedeanClass.mk_zpow IsOrderedRing => IsOrderedCancelAddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArchimedeanClass.mk_inv IsOrderedRing => IsStrictOrderedRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArchimedeanClass.mk_zpow IsOrderedRing => IsStrictOrderedRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt max_div_div_right IsStrictOrderedRing => PosMulMono by rfl, simp, aesop, exact?, grind
#fh_home_attempt min_div_div_right IsStrictOrderedRing => PosMulMono by rfl, simp, aesop, exact?, grind
#fh_home_attempt max_div_div_right IsStrictOrderedRing => PosMulReflectLE by rfl, simp, aesop, exact?, grind
#fh_home_attempt min_div_div_right IsStrictOrderedRing => PosMulReflectLE by rfl, simp, aesop, exact?, grind
#fh_home_attempt max_div_div_right IsStrictOrderedRing => PosMulStrictMono by rfl, simp, aesop, exact?, grind
#fh_home_attempt min_div_div_right IsStrictOrderedRing => PosMulStrictMono by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.ofColex_top LinearOrder => OrderTop by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.toColex_univ LinearOrder => OrderTop by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.ofColex_top LinearOrder => WellFoundedGT by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.toColex_univ LinearOrder => WellFoundedGT by rfl, simp, aesop, exact?, grind
#fh_home_attempt Metric.NonemptyCompacts.dist_eq MetricSpace => EMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Metric.lipschitz_infDist_set MetricSpace => EMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_pow Monoid => NPow by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_pow Monoid => NPow by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_pow Monoid => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_pow Monoid => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Memℓp.summable_of_one NormedAddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt lp.norm_tsum_le NormedAddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Memℓp.summable_of_one NormedAddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt lp.norm_tsum_le NormedAddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Memℓp.summable_of_one NormedAddCommGroup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt lp.norm_tsum_le NormedAddCommGroup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Memℓp.summable_of_one NormedAddCommGroup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt lp.norm_tsum_le NormedAddCommGroup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt hnot_eq_sInf_codisjoint Order.Coframe => CompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sdiff_eq_sInf Order.Coframe => CompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt hnot_eq_sInf_codisjoint Order.Coframe => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sdiff_eq_sInf Order.Coframe => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt hnot_eq_sInf_codisjoint Order.Coframe => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt sdiff_eq_sInf Order.Coframe => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt hnot_eq_sInf_codisjoint Order.Coframe => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt sdiff_eq_sInf Order.Coframe => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_eq_sSup_disjoint Order.Frame => CompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt himp_eq_sSup Order.Frame => CompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_eq_sSup_disjoint Order.Frame => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt himp_eq_sSup Order.Frame => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_eq_sSup_disjoint Order.Frame => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt himp_eq_sSup Order.Frame => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_eq_sSup_disjoint Order.Frame => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt himp_eq_sSup Order.Frame => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArithmeticFunction.coe_zeta_mul_comm Semiring => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArithmeticFunction.natCoe_mul Semiring => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArithmeticFunction.coe_zeta_mul_comm Semiring => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArithmeticFunction.natCoe_mul Semiring => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArithmeticFunction.coe_zeta_mul_comm Semiring => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArithmeticFunction.natCoe_mul Semiring => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArithmeticFunction.coe_zeta_mul_comm Semiring => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArithmeticFunction.natCoe_mul Semiring => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddMonoid.End.zero_apply AddCommMonoid => AddZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.bot_eq_zero AddCommMonoid => Lean.Grind.AddCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.bot_eq_zero AddCommMonoid => NegZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.HasAntidiagonal.antidiagonal.fst_le AddCommMonoid => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_natCast AddCommMonoidWithOne => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_natCast AddCommMonoidWithOne => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_natCast AddCommMonoidWithOne => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_natCast AddCommMonoidWithOne => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_le_hnot BiheytingAlgebra => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_le_hnot BiheytingAlgebra => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_le_hnot BiheytingAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_le_hnot BiheytingAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt ofBoolRing_neg BooleanAlgebra => HasDistribNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt ofBoolRing_neg BooleanAlgebra => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.FactorSet.coe_add CommMonoidWithZero => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.FactorSet.coe_add CommMonoidWithZero => Submonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.FactorSet.coe_add CommMonoidWithZero => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.FactorSet.coe_add CommMonoidWithZero => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt iSup_symmDiff_iSup_le CompleteBooleanAlgebra => CompleteAtomicBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt iSup_symmDiff_iSup_le CompleteBooleanAlgebra => CompletelyDistribLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt iSup_symmDiff_iSup_le CompleteBooleanAlgebra => Order.Coframe by rfl, simp, aesop, exact?, grind
#fh_home_attempt iSup_symmDiff_iSup_le CompleteBooleanAlgebra => Order.Frame by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.untrop_sum ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
