/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 6 of 6 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt orderOf_eq_zero_iff_eq_zero GroupWithZero => DivInvMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt orderOf_eq_zero_iff_eq_zero GroupWithZero => MonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt Metric.lipschitz_infDist_set MetricSpace => EMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Metric.lipschitz_infDist_set MetricSpace => PseudoMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulAut.smul_def Monoid => MulOne by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulAut.smul_def Monoid => MulOneClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulAut.smul_def Monoid => Semigroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt CStarMatrix.uniformEmbedding_ofMatrix NonUnitalCStarAlgebra => EMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt CStarMatrix.uniformEmbedding_ofMatrix NonUnitalCStarAlgebra => NonUnitalNormedRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt CStarMatrix.uniformEmbedding_ofMatrix NonUnitalCStarAlgebra => NonUnitalSeminormedRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt CStarMatrix.uniformEmbedding_ofMatrix NonUnitalCStarAlgebra => PseudoEMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.tendsto_atBot_iff_leadingCoeff_nonpos NormedField => CommRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.tendsto_atBot_iff_leadingCoeff_nonpos NormedField => EuclideanDomain by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.tendsto_atBot_iff_leadingCoeff_nonpos NormedField => NormedCommRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.tendsto_atBot_iff_leadingCoeff_nonpos NormedField => NormedDivisionRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt sdiff_eq_sInf Order.Coframe => CoheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt himp_eq_sSup Order.Frame => HeytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt UniformSpace.Completion.coe_mul Ring => NonAssocRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt UniformSpace.Completion.coe_mul Ring => NonUnitalRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Fintype.toOrderBot.congr_simp SemilatticeInf => PartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Fintype.toOrderBot.congr_simp SemilatticeInf => Preorder by rfl, simp, aesop, exact?, grind
