/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 3 of 6 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt ReaderT.run_seqLeft Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt ReaderT.run_seqRight Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt SatisfiesM_ReaderT_eq Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt StateRefT'.lift_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt StateT.map_const Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt StateT.run_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt Std.Iterators.PostconditionT.property_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt Std.Iterators.PostconditionT.pure_eq_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt Std.Iterators.ULiftT.run_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt WriterT.run_map Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt WriterT.run_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt Matrix.conjTranspose_zsmul AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imI_sub AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imJ_sub AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imK_sub AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.im_sub AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.mk_sub_mk AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.re_sub AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_neg AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_sub AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_neg AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_sub AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Complex.coe_smul AddCommGroup => SubtractionCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Module.isTorsionFree_int_iff_isAddTorsionFree AddCommGroup => SubtractionCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_add AddCommGroup => SubtractionCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_neg AddCommGroup => SubtractionCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_sub AddCommGroup => SubtractionCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_add AddCommGroup => SubtractionCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_neg AddCommGroup => SubtractionCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_sub AddCommGroup => SubtractionCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_neg AddCommGroup => SubtractionCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_sub AddCommGroup => SubtractionCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imI_sub AddGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imJ_sub AddGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imK_sub AddGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.mk_sub_mk AddGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.re_sub AddGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_neg AddGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_sub AddGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_neg AddGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_sub AddGroup => SubNegZeroMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_add AddCommGroup => AddGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_neg AddCommGroup => AddGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_sub AddCommGroup => AddGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_add AddCommGroup => AddGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_neg AddCommGroup => AddGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_sub AddCommGroup => AddGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_neg AddCommGroup => AddGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_sub AddCommGroup => AddGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt Matrix.conjTranspose_zsmul AddGroup => SubNegMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imI_sub AddGroup => SubNegMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imJ_sub AddGroup => SubNegMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imK_sub AddGroup => SubNegMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.mk_sub_mk AddGroup => SubNegMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.re_sub AddGroup => SubNegMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_sub AddGroup => SubNegMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_sub AddGroup => SubNegMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt codisjoint_iff_compl_le_left BooleanAlgebra => BiheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt codisjoint_iff_compl_le_right BooleanAlgebra => BiheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_inf BooleanAlgebra => BiheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_symmDiff_self BooleanAlgebra => BiheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt symmDiff_compl_self BooleanAlgebra => BiheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt symmDiff_top BooleanAlgebra => BiheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt top_sdiff BooleanAlgebra => BiheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt top_symmDiff BooleanAlgebra => BiheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.comp_sdiff_comp GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_bot GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_inf_lift GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_sdiff_lift GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_sup_lift GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_le_lift GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_lt_lift GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Disjoint.symmDiff_left GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.DegLex.single_strictAnti LinearOrder => PartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.Lex.single_strictAnti LinearOrder => PartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedGE_insertionSort LinearOrder => PartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedGE_mergeSort LinearOrder => PartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedLE_insertionSort LinearOrder => PartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedLE_mergeSort LinearOrder => PartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.apply_le_of_toColex LinearOrder => PartialOrder by rfl, simp, aesop, exact?, grind
