/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 3 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt mul_eq_mul_iff_eq_and_eq_of_pos PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt mul_eq_mul_iff_eq_and_eq_of_pos' PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt mul_inv_le_iff₀ PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt mul_inv_lt_iff₀ PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt mul_lt_mul_of_neg_left PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt mul_lt_mul_of_neg_right PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt mul_self_lt_mul_self PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt posMulMono_iff_posMulStrictMono PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt posMulReflectLE_iff_posMulReflectLT PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt pow_pos PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt pow_succ_pos PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt sq_pos_of_pos PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt strictMono_mul_left_of_pos PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt strictMono_mul_right_of_pos PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt wcovBy_eq_reflGen_covBy PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt zpow_left_mono PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt zpow_left_monoOn₀ PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt zpow_right_mono PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt zsmul_left_mono PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt zsmul_mono_right PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.op_le_op Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.unop_le_unop Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt AddUnits.val_le_val Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt BddAbove.dual Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt BddBelow.dual Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Directed.extend_bot Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Filter.IsBoundedUnder.eventually_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Filter.isBoundedUnder_of_eventually_ge Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Filter.isBoundedUnder_of_eventually_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.single_le_single Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.single_nonneg Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.single_nonpos Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Flag.le_or_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Function.const_le_one_of_le_one Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Function.const_nonneg_of_nonneg Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Function.const_nonpos_of_nonpos Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Function.one_le_const_of_one_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Interval.bot_div Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Interval.coe_le_coe Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Interval.div_bot Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Interval.dual_top Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsAntichain.eq_setOf_maximal Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsChain.exists_subset_flag Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsCofinalFor.nonempty Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsCoinitialFor.nonempty Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsGLB.bddBelow Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsGLB.dual Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsGreatest.bddAbove Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsGreatest.dual Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsGreatest.isLUB Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsGreatest.maximal Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsGreatest.mono Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsGreatest.nonempty Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLUB.bddAbove Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLUB.dual Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLeast.bddBelow Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLeast.dual Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLeast.isGLB Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLeast.minimal Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLeast.mono Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLeast.nonempty Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLowerSet.bot_mem Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLowerSet.lowerBounds_subset Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLowerSet.top_mem Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsUpperSet.bot_mem Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsUpperSet.top_mem Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsUpperSet.upperBounds_subset Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Left.nsmul_nonneg Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Left.one_le_pow_of_le Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.op_le_op Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.unop_le_unop Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.coe_div_interval Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.coe_one_interval Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.coe_top_interval Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.coe_zero_interval Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.dual_top Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.fst_div Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.fst_natCast Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.fst_nsmul Preorder => LE by rfl, simp, aesop, exact?
#fh_home_attempt NonemptyInterval.fst_one Preorder => LE by rfl, simp, aesop, exact?
