/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 23 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Continuous.sigmoid NormedAddCommGroup => TopologicalSpace by rfl, simp, aesop, exact?
#fh_home_attempt spectrum.algebraMap_eq_of_mem NormedAlgebra => Algebra by rfl, simp, aesop, exact?
#fh_home_attempt Bornology.isVonNBounded_pi_iff NormedDivisionRing => SeminormedRing by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.tendsto_atBot_iff_leadingCoeff_nonpos NormedField => Ring by rfl, simp, aesop, exact?
#fh_home_attempt hnot_eq_sInf_codisjoint Order.Coframe => CoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt sup_sInf_eq Order.Coframe => CompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt sdiff_eq_sInf Order.Coframe => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt compl_eq_sSup_disjoint Order.Frame => HeytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt summable_pow_div_add RCLike => NormedDivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt Memℓp.bilin_of_zero_left RCLike => NormedField by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.CancelDenoms.add_subst Ring => Distrib by rfl, simp, aesop, exact?
#fh_home_attempt not_ringChar_dvd_of_invertible Ring => NonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt SSet.Subcomplex.Pairing.strongInnerAnodyneExtensions SSet.Subcomplex.Pairing.IsRegular => SSet.Subcomplex.Pairing.IsProper by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.div_congr Semifield => Div by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.div_pf Semifield => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.inv_congr Semifield => Inv by rfl, simp, aesop, exact?
#fh_home_attempt Fintype.toOrderBot.congr_simp SemilatticeInf => LE by rfl, simp, aesop, exact?
#fh_home_attempt Set.PairwiseDisjoint.attach SemilatticeInf => PartialOrder by rfl, simp, aesop, exact?
#fh_home_attempt eventually_ne_of_tendsto_norm_atTop' SeminormedGroup => Norm by rfl, simp, aesop, exact?
#fh_home_attempt Asymptotics.isBigOWith_of_eq_mul SeminormedRing => NonUnitalSeminormedRing by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.FieldSimp.subst_add Semiring => Distrib by rfl, simp, aesop, exact?
#fh_home_attempt List.le_total Std.Asymm => Std.Total by rfl, simp, aesop, exact?
#fh_home_attempt Matrix.IsDiag.sub SubtractionMonoid => SubNegZeroMonoid by rfl, simp, aesop, exact?
