/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 20 of 20 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Finset.untrop_sum ConditionallyCompleteLinearOrder => ConditionallyCompletePartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.untrop_sum ConditionallyCompleteLinearOrder => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.untrop_sum ConditionallyCompleteLinearOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_nnratCast Field => DivisionSemiring by rfl, simp, aesop, exact?, grind
#fh_home_attempt Filter.cofinite_eq_bot Finite => OrderBot by rfl, simp, aesop, exact?, grind
#fh_home_attempt Filter.cofinite_eq_bot Finite => WellFoundedLT by rfl, simp, aesop, exact?, grind
#fh_home_attempt Filter.cofinite_eq_bot Finite => WellQuasiOrderedLE by rfl, simp, aesop, exact?, grind
#fh_home_attempt Fintype.toOrderBot.congr_simp Fintype => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_bot GeneralizedBooleanAlgebra => OrderBot by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_bot GeneralizedBooleanAlgebra => WellFoundedLT by rfl, simp, aesop, exact?, grind
#fh_home_attempt orderOf_eq_zero_iff_eq_zero GroupWithZero => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt orderOf_eq_zero_iff_eq_zero GroupWithZero => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Metric.NonemptyCompacts.dist_eq MetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Metric.lipschitz_infDist_set MetricSpace => PseudoMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt uzpow_zero Module => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt uzpow_zero Module => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt uzpow_zero Module => MulZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt uzpow_zero Module => MulZeroOneClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulAut.smul_def Monoid => Distrib by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulAut.smul_def Monoid => MulOne by rfl, simp, aesop, exact?, grind
#fh_home_attempt FiniteMultiplicity.ne_zero MonoidWithZero => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt FiniteMultiplicity.ne_zero MonoidWithZero => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt FiniteMultiplicity.ne_zero MonoidWithZero => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt FiniteMultiplicity.ne_zero MonoidWithZero => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt CStarMatrix.uniformEmbedding_ofMatrix NonUnitalCStarAlgebra => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt CStarMatrix.uniformEmbedding_ofMatrix NonUnitalCStarAlgebra => IsScalarTower by rfl, simp, aesop, exact?, grind
#fh_home_attempt CStarMatrix.uniformEmbedding_ofMatrix NonUnitalCStarAlgebra => PseudoEMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt CStarMatrix.uniformEmbedding_ofMatrix NonUnitalCStarAlgebra => PseudoMetricSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.tendsto_atBot_iff_leadingCoeff_nonpos NormedField => AbsoluteValue by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.tendsto_atBot_iff_leadingCoeff_nonpos NormedField => NontriviallyNormedField by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.tendsto_atBot_iff_leadingCoeff_nonpos NormedField => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.tendsto_atBot_iff_leadingCoeff_nonpos NormedField => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Fintype.toOrderBot.congr_simp SemilatticeInf => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt TopologicalSpace.Closeds.noncompactSpace_iff UniformSpace => UniformSpace.Core by rfl, simp, aesop, exact?, grind
