/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 6 of 20 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Topology.scottHausdorff_le_scott Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.upperSet_le_scott Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Units.val_le_val Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Units.val_lt_val Preorder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.ofColex_top LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.toColex_univ LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.sortedGT_sort LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.sortedLT_sort LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.DegLex.single_strictAnti LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.Lex.single_strictAnti LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedGE_insertionSort LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedGE_mergeSort LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedLE_insertionSort LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedLE_mergeSort LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt NNRat.Nonneg.coe_ofScientific LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_div LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_inv LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_nnqsmul LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_nnratCast LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_zpow LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.inv_mk LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_div_mk LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_nnqsmul LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_zpow LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.apply_le_of_toColex LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.apply_le_of_toLex LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.toLex_monotone LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.toLex_strictMono LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Positive.coe_inv LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Positive.coe_zpow LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.coe_div LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.coe_zpow LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.normSq_div LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.normSq_zpow LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Tropical.trop_max_def LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Tropical.trop_sup_def LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Tropical.untrop_max LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Tropical.untrop_sup LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.coe_max LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.coe_min LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_max LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_min LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt leOnePart_eq_ite LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt leOnePart_eq_ite_lt LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt negPart_eq_ite LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt negPart_eq_ite_lt LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt oneLePart_eq_ite LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt oneLePart_eq_ite_lt LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt posPart_eq_ite LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt posPart_eq_ite_lt LinearOrder => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.ofColex_top LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.toColex_univ LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.sortedGT_sort LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.sortedLT_sort LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.DegLex.single_strictAnti LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.Lex.single_strictAnti LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedGE_insertionSort LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedGE_mergeSort LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedLE_insertionSort LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedLE_mergeSort LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt NNRat.Nonneg.coe_ofScientific LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_div LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_inv LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_nnqsmul LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_nnratCast LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_zpow LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.inv_mk LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_div_mk LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_nnqsmul LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_zpow LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.apply_le_of_toColex LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.apply_le_of_toLex LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.toLex_monotone LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.toLex_strictMono LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Positive.coe_inv LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Positive.coe_zpow LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.coe_div LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.coe_zpow LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.normSq_div LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.normSq_zpow LinearOrder => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
