/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 2 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Set.Ico_eq_singleton_left_iff PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Ico_sdiff_left PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Iic_sdiff_right PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Iio_eq_singleton_bot_iff PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Ioc.coe_le_one PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Ioc.coe_pos PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Ioi_eq_singleton_top_iff PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Ioo.lt_one PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.Ioo.pos PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.add_mem_Icc_iff_left PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.add_mem_Icc_iff_right PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.indicator_le_self PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.inv_Ici PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.inv_Iic PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.inv_mem_Icc_iff PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.mulIndicator_le_self PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.neg_Ici PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.neg_Iic PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.neg_mem_Icc_iff PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_add_const_Ici PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_add_const_Iic PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_add_Ici PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_add_Iic PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_div_Ici PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_div_Iic PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_mul_Ici PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_mul_Iic PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_sub_Ici PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_sub_Iic PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_mul_const_Ici PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_mul_const_Iic PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.sub_mem_Icc_iff_left PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.sub_mem_Icc_iff_right PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.sub_mem_Icc_zero_iff_right PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.sub_mem_Ico_zero_iff_right PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.sub_mem_Ioc_zero_iff_right PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt Set.sub_mem_Ioo_zero_iff_right PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt UpperSet.Ioi_eq_top PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.Icc_bot_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.Icc_coe_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.Ico_bot_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.Ico_coe_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.Ioc_bot_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.Ioc_coe_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.Ioo_bot_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.Ioo_coe_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.one_le_iff_pos PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.Icc_coe_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.Icc_coe_top PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.Ico_coe_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.Ico_coe_top PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.Ioc_coe_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.Ioc_coe_top PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.Ioo_coe_coe PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.Ioo_coe_top PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.pow_right_strictMono PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt bot_covBy_iff PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt countableSupClosure_singleton PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt covBy_iff_atom_Ici PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt covBy_iff_coatom_Iic PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt eventuallyEq_of_isMinFilter_of_isMaxFilter PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt exists_covBy_seq_of_wellFoundedLT_wellFoundedGT_of_le PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt finprod_le_finprod PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt finprod_le_finprod' PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt finsum_le_finsum' PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt inv_mul_le_iff₀ PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt inv_mul_lt_iff₀ PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt inv_nonneg PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt inv_pos PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt isUpperSet_iff_Ioi_subset PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt le_inv_mul_iff₀ PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt le_mul_inv_iff₀ PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt lt_inv_mul_iff₀ PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt lt_mul_inv_iff₀ PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt lt_mul_left PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt lt_mul_right PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt mulPosMono_iff_mulPosStrictMono PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt mulPosReflectLE_iff_mulPosReflectLT PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt mul_add_mul_le_mul_add_mul PartialOrder => Preorder by rfl, simp, aesop, exact?
#fh_home_attempt mul_add_mul_lt_mul_add_mul PartialOrder => Preorder by rfl, simp, aesop, exact?
