/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 8 of 13 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 400000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt div_lt_one Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_strictAntiOn Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_div_self Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_one_div Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt lt_one_div Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt monotone_div_right_of_nonneg Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt one_div_le Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt one_div_le_one_div_of_le Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt one_div_lt Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt one_le_div Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt one_lt_div Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt strictMono_div_right_of_pos Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Ideal.is_fg_degreeLE CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsBezout.gcd_eq_sum CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.add_modByMonic CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.exists_multiset_roots CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.le_rootMultiplicity_iff CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.leadingCoeff_divByMonic_of_monic CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.modByMonic_eq_of_dvd_sub CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.rootMultiplicity_eq_zero_iff CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.smul_modByMonic CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Ring.ord_mul_of_isUnit_left CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_pow_sub_pow_le CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_unit_intCast CommRing => Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt SemiconjBy.zpow_right Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.smul_inter_nonempty_iff' Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt leOnePart_eq_inv Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt leOnePart_eq_ite Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt leOnePart_eq_ite_lt Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt leOnePart_eq_one Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt leOnePart_le_one Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_zpow_mul Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt oneLePart_eq_ite_lt Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt oneLePart_of_one_lt_oneLePart Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt pow_intGCD_eq_one Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt pow_natAbs_eq_one Group => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.inv_op_smul_finset_distrib Group => DivisionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.inv_smul_finset_distrib Group => DivisionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.small_pow_of_small_tripling Group => DivisionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.inv_op_smul_set_distrib Group => DivisionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.inv_smul_set_distrib Group => DivisionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.mem_smul_set_inv Group => DivisionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt SimpleGraph.mulCayley_inv Group => DivisionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_eq_self_of_exponent_two Group => DivisionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_eq_self_of_orderOf_eq_two Group => DivisionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt max_one_div_max_inv_one_eq_self Group => DivisionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_div_Ici IsOrderedMonoid => MulLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_div_Iic IsOrderedMonoid => MulLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_mul_Ici IsOrderedMonoid => MulLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_mul_Iic IsOrderedMonoid => MulLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_div IsOrderedMonoid => MulLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_div_le IsOrderedMonoid => MulLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_eq IsOrderedMonoid => MulLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_mul' IsOrderedMonoid => MulLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mabs_pow IsOrderedMonoid => MulLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt zpow_right_mono IsOrderedMonoid => MulLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_le_one Semifield => DivisionSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_lt_one Semifield => DivisionSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_lt_zero Semifield => DivisionSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_nonneg Semifield => DivisionSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_nonpos Semifield => DivisionSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_pos Semifield => DivisionSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.ceil_cast Semifield => DivisionSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.not_cast_lt_zero Semifield => DivisionSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.one_le_cast Semifield => DivisionSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.one_lt_cast Semifield => DivisionSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.Nonempty.zpow DivisionMonoid => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.empty_zpow DivisionMonoid => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.inv_subset_div_right DivisionMonoid => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.singleton_zpow DivisionMonoid => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Nonempty.zpow DivisionMonoid => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.empty_zpow DivisionMonoid => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.inv_subset_div_right DivisionMonoid => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.univ_div_univ DivisionMonoid => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt neg_div DivisionMonoid => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.closedEBall_zero EMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.ediam_pos_iff EMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.ediam_pos_iff' EMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.eventually_nhds_zero_forall_closedEBall_subset EMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.isSeparated_zero EMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
