/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 11 of 13 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 400000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt le_iInf CompleteLattice => CompleteSemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sInf_eq_of_forall_ge_of_forall_gt_exists_lt CompleteLattice => CompleteSemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt DedekindCut.principal_sSup_left CompleteLattice => CompleteSemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsLUB.iSup_eq CompleteLattice => CompleteSemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt iSup_le CompleteLattice => CompleteSemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sSup_eq_of_forall_le_of_forall_lt_exists_gt CompleteLattice => CompleteSemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt iSup₂_eq_top CompleteLinearOrder => CompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt iUnion_Ici_eq_Ici_iInf CompleteLinearOrder => CompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt iUnion_Ici_eq_Ioi_iInf CompleteLinearOrder => CompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isSaddlePointOn_iff CompleteLinearOrder => CompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt AlgebraicGeometry.pullback_of_geometrically Field => CommRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt AlgebraicGeometry.pullback_of_geometrically' Field => CommRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MonomialOrder.sPolynomial_decomposition' Field => CommRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.X_sub_C_dvd_derivative_of_X_sub_C_dvd_divByMonic Field => CommRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_mul_sign IsStrictOrderedRing => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt self_mul_sign IsStrictOrderedRing => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sign_mul_abs IsStrictOrderedRing => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sign_mul_self IsStrictOrderedRing => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Ici_mul_Ici_eq Monoid => Mul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isAddRegular_ofMul Monoid => Mul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isRegular_toMul Monoid => Mul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt min_mul_distrib Monoid => Mul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsOfFinOrder.norm_eq_one NormedRing => SeminormedRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NormedAlgebra.Complex.exists_norm_sub_smul_one_eq_zero NormedRing => SeminormedRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.supNorm_eq_zero_iff NormedRing => SeminormedRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt spectrum.algebraMap_eq_of_mem NormedRing => SeminormedRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.AEStronglyMeasurable.nnnorm SeminormedAddCommGroup => SeminormedAddGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.AEStronglyMeasurable.norm SeminormedAddCommGroup => SeminormedAddGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.StronglyMeasurable.nnnorm SeminormedAddCommGroup => SeminormedAddGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.StronglyMeasurable.norm SeminormedAddCommGroup => SeminormedAddGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt CharTwo.add_self_eq_zero Semiring => NonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Meta.NormNum.isNat_mul Semiring => NonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt add_le_mul_of_left_le_right Semiring => NonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt add_le_mul_of_right_le_left Semiring => NonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.FinMeasAdditive.neg AddGroup => SubtractionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt neg_eq_self_of_addOrderOf_eq_two AddGroup => SubtractionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt neg_eq_self_of_exponent_two AddGroup => SubtractionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isAddRegular_toAdd AddMonoid => Add by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isRegular_ofAdd AddMonoid => Add by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt min_add_distrib AddMonoid => Add by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt CategoryTheory.ObjectProperty.ne_bot_iff_exists CategoryTheory.Category => CategoryTheory.CategoryStruct by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt CategoryTheory.effectiveEpiFamilyStructCompIso_aux CategoryTheory.Category => CategoryTheory.CategoryStruct by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt CategoryTheory.isCardinalFiltered_iff_aux₁ CategoryTheory.Category => CategoryTheory.CategoryStruct by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.one_le_prod CommMonoidWithZero => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt notMem_nonZeroDivisors_iff_left CommMonoidWithZero => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt notMem_nonZeroDivisors_iff_right CommMonoidWithZero => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.Algebra.isNat_zero_eq CommSemiring => AddMonoidWithOne by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.Ring.cast_pos CommSemiring => AddMonoidWithOne by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.Ring.cast_zero CommSemiring => AddMonoidWithOne by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.coeff_inv_units Field => Semifield by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WeierstrassCurve.Jacobian.X_eq_iff Field => Semifield by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WeierstrassCurve.Jacobian.Y_eq_iff Field => Semifield by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.inv_univ InvolutiveInv => Inv by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.mem_inv' InvolutiveInv => Inv by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.image_op_inv InvolutiveInv => Inv by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Associates.le_of_mul_le_mul_left IsCancelMulZero => IsLeftCancelMulZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsRegular.of_ne_zero IsCancelMulZero => IsLeftCancelMulZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt divisor_closure_eq_closure IsCancelMulZero => IsLeftCancelMulZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Function.Injective.of_lt_imp_ne LinearOrder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt LT.lt.exists_disjoint_Iio_Ioi LinearOrder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt eq_iff_eq_of_lt_iff_lt_of_gt_iff_gt LinearOrder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ContractingWith.fixedPoint_unique' MetricSpace => EMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ContractingWith.one_sub_K_pos MetricSpace => EMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Perfect.small_diam_splitting MetricSpace => EMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Asymptotics.isEquivalent_iff_exists_eq_mul NormedField => NormedDivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Asymptotics.isTheta_of_div_tendsto_nhds_ne_zero NormedField => NormedDivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt EulerProduct.one_sub_inv_eq_geometric_of_summable_norm NormedField => NormedDivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ConvexOn.isBoundedUnder_abs NormedSpace => Module by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt posTangentConeAt_mono NormedSpace => Module by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt real_linearMap_map_smul_complex NormedSpace => Module by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.AEStronglyMeasurable.edist PseudoMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.infEDist_eq_top_iff PseudoMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.mem_nhdsSet_iff PseudoMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt CharP.prime_ringChar Ring => NonAssocRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsSelfAdjoint.intCast Ring => NonAssocRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt RingCon.range_mk' Ring => NonAssocRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsSelfAdjoint.div StarRing => StarMul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsStarProjection.mul StarRing => StarMul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Unitary.mem_iff_eq_one_or_eq_neg_one StarRing => StarMul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt AddSubmonoid.mem_nhds_zero AddCommMonoid => AddZeroClass by norm_num, omega, positivity, order, nlinarith, grind
