/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 14 of 20 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt sup_bihimp_bihimp GeneralizedHeytingAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt sup_inf_bihimp GeneralizedHeytingAlgebra => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_bihimp_sup GeneralizedHeytingAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_eq_top GeneralizedHeytingAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_himp_eq_inf GeneralizedHeytingAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_inf_sup GeneralizedHeytingAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_triangle GeneralizedHeytingAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt himp_bihimp_eq_inf GeneralizedHeytingAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt sup_bihimp_bihimp GeneralizedHeytingAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt sup_inf_bihimp GeneralizedHeytingAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_add AddCommGroup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_eq_zero_iff AddCommGroup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_neg AddCommGroup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_period AddCommGroup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Complex.coe_smul AddCommGroup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt DistribSMul.toAddMonoidHom_eq_zsmulAddGroupHom AddCommGroup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Module.isTorsionFree_int_iff_isAddTorsionFree AddCommGroup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_add AddCommGroup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_eq_zero_iff AddCommGroup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_neg AddCommGroup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_period AddCommGroup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Complex.coe_smul AddCommGroup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt DistribSMul.toAddMonoidHom_eq_zsmulAddGroupHom AddCommGroup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Module.isTorsionFree_int_iff_isAddTorsionFree AddCommGroup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imI_sub AddGroup => Lean.Grind.AddCommGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imJ_sub AddGroup => Lean.Grind.AddCommGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imK_sub AddGroup => Lean.Grind.AddCommGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.mk_sub_mk AddGroup => Lean.Grind.AddCommGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.re_sub AddGroup => Lean.Grind.AddCommGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_sub AddGroup => Lean.Grind.AddCommGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_sub AddGroup => Lean.Grind.AddCommGroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imI_sub AddGroup => Lean.Grind.IntModule by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imJ_sub AddGroup => Lean.Grind.IntModule by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.imK_sub AddGroup => Lean.Grind.IntModule by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.mk_sub_mk AddGroup => Lean.Grind.IntModule by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.re_sub AddGroup => Lean.Grind.IntModule by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_sub AddGroup => Lean.Grind.IntModule by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_sub AddGroup => Lean.Grind.IntModule by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nucleus.sInf_apply CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_insert CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_pair CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_union CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_insert CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_pair CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_union CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nucleus.sInf_apply CompleteLattice => ConditionallyCompletePartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_insert CompleteLattice => ConditionallyCompletePartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_pair CompleteLattice => ConditionallyCompletePartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_union CompleteLattice => ConditionallyCompletePartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_insert CompleteLattice => ConditionallyCompletePartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_pair CompleteLattice => ConditionallyCompletePartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_union CompleteLattice => ConditionallyCompletePartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nucleus.sInf_apply CompleteLattice => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_insert CompleteLattice => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_pair CompleteLattice => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_union CompleteLattice => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_insert CompleteLattice => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_pair CompleteLattice => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_union CompleteLattice => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nucleus.sInf_apply CompleteLattice => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_insert CompleteLattice => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_pair CompleteLattice => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_union CompleteLattice => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_insert CompleteLattice => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_pair CompleteLattice => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt sSup_union CompleteLattice => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.compl_union Fintype => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.inter_compl Fintype => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.piecewise_compl Fintype => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.subset_compl_comm Fintype => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.subset_compl_iff_disjoint_left Fintype => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.subset_compl_iff_disjoint_right Fintype => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Set.Finite.toFinset_compl Fintype => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.comp_sdiff_comp GeneralizedBooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_inf_lift GeneralizedBooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_sdiff_lift GeneralizedBooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_sup_lift GeneralizedBooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_le_lift GeneralizedBooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_lt_lift GeneralizedBooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Disjoint.symmDiff_left GeneralizedBooleanAlgebra => Vector by rfl, simp, aesop, exact?, grind
