/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 9 of 13 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 400000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Metric.packingNumber_zero EMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt TopologicalSpace.Closeds.continuous_infEDist EMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt edist_ne_top_of_mem_ball EMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt nhds_eq_nhds_emetric_ball EMetricSpace => PseudoEMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.isWF_insert Preorder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithTop.isSuccPrelimit_top Preorder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithZero.denselyOrdered_iff Preorder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithZero.exists_ne_zero_and_lt Preorder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithZero.exp_lt_exp Preorder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithZero.log_lt_log Preorder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithZero.lt_exp_of_log_lt Preorder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt cmp_swap Preorder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt covBy_irrefl Preorder => LT by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt cmp_mul_pos_left Semiring => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt cmp_mul_pos_right Semiring => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt max_mul_of_nonneg Semiring => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt min_mul_of_nonneg Semiring => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_max_of_nonneg Semiring => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_min_of_nonneg Semiring => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_self_inj Semiring => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_self_lt_mul_self_iff Semiring => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt nonneg_le_nonneg_of_sq_le_sq Semiring => MonoidWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_nonneg_iff_of_pos_left Semiring => MulZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_nonneg_iff_of_pos_right Semiring => MulZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt nonneg_and_nonneg_or_nonpos_and_nonpos_of_mul_nonneg Semiring => MulZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt nonneg_of_mul_nonneg_left Semiring => MulZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt nonneg_of_mul_nonneg_right Semiring => MulZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt nonpos_of_mul_nonneg_left Semiring => MulZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt nonpos_of_mul_nonneg_right Semiring => MulZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt nonpos_of_mul_nonpos_left Semiring => MulZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt nonpos_of_mul_nonpos_right Semiring => MulZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.degree_eq_degree_of_associated CommRing => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.isUnit_C_add_X_mul_iff CommRing => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.splits_X_mul CommRing => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.splits_mul' CommRing => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.splits_mul_iff_left CommRing => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.splits_mul_iff_right CommRing => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.units_coeff_zero_smul CommRing => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ValuationRing.unique_irreducible CommRing => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.bliminf_antitone CompleteLattice => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.bliminf_antitone_filter CompleteLattice => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.blimsup_mono CompleteLattice => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.blimsup_monotone_filter CompleteLattice => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.liminf_le_of_frequently_le' CompleteLattice => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.limsup_eq_sInf_sSup CompleteLattice => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.mono_bliminf' CompleteLattice => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.mono_blimsup' CompleteLattice => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ExponentExists.isTorsion Group => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.isUnit_iff_singleton Group => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.isUnit_iff_singleton Group => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.isUnit_iff_singleton_aux Group => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsTorsion.exponentExists Group => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Monoid.minOrder_eq_top Group => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.isUnit_iff_singleton Group => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt orderOf_dvd_natCard Group => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.Nonempty.zsmul SubtractionMonoid => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.neg_subset_sub_right SubtractionMonoid => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.zsmul_empty SubtractionMonoid => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.zsmul_singleton SubtractionMonoid => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.Abel.unfold_sub SubtractionMonoid => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.neg_subset_sub_right SubtractionMonoid => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.univ_sub_univ SubtractionMonoid => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.zsmul_empty SubtractionMonoid => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt DividedPowers.exp_add' CommSemiring => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Nat.castChoose_eq CommSemiring => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.Monic.leadingCoeff_notMem CommSemiring => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.Monic.natDegree_pos CommSemiring => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.eq_zero_of_mul_eq_zero_of_smul CommSemiring => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt PowerSeries.trunc_coe_eq_self CommSemiring => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Submodule.smul_le_span CommSemiring => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.IsCobounded.of_frequently_ge LinearOrder => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.inf'_pow LinearOrder => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.nsmul_inf' LinearOrder => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.not_isMax_pred LinearOrder => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt infIrred_iff_not_isMax LinearOrder => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt infPrime_iff_not_isMax LinearOrder => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inf_ind LinearOrder => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithTop.isGLB_sInf ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ciInf_le' ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt csInf_le' ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
