/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 10 of 20 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Finset.subset_compl_comm Fintype => CompleteBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.subset_compl_iff_disjoint_left Fintype => CompleteBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.subset_compl_iff_disjoint_right Fintype => CompleteBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Fintype.toOrderBot.congr_simp Fintype => CompleteBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Set.Finite.toFinset_compl Fintype => CompleteBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt ExceptT.run_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt ReaderT.run_map Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt ReaderT.run_mapConst Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt ReaderT.run_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt ReaderT.run_seq Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt ReaderT.run_seqLeft Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt ReaderT.run_seqRight Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt SatisfiesM_ReaderT_eq Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt StateRefT'.lift_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt StateT.map_const Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt StateT.run_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt Std.Iterators.PostconditionT.property_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt Std.Iterators.PostconditionT.pure_eq_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt Std.Iterators.ULiftT.run_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt WriterT.run_map Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt WriterT.run_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_add AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_eq_zero_iff AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_neg AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_period AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Complex.coe_smul AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt DistribSMul.toAddMonoidHom_eq_zsmulAddGroupHom AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Module.isTorsionFree_int_iff_isAddTorsionFree AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_add AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_neg AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_sub AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_add AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_neg AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_sub AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_neg AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_sub AddCommGroup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_add AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_eq_zero_iff AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_neg AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddCircle.coe_period AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Complex.coe_smul AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt DistribSMul.toAddMonoidHom_eq_zsmulAddGroupHom AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Module.isTorsionFree_int_iff_isAddTorsionFree AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_add AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_neg AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_sub AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_add AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_neg AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_sub AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_neg AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_sub AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentPolynomial.C_eq_algebraMap CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentPolynomial.algebraMap_X_pow CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentPolynomial.algebraMap_eq_toLaurent CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentSeries.coe_algebraMap CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt MvPowerSeries.c_eq_algebraMap CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.C_eq_algebraMap CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.algebraMap_eq CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.algebraMap_pi_self_eq_eval CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.coe_algebraMap_eq_CC CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt PowerSeries.C_eq_algebraMap CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt PowerSeries.algebraMap_eq CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.C_pow CommSemiring => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentPolynomial.C_eq_algebraMap CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentPolynomial.algebraMap_X_pow CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentPolynomial.algebraMap_eq_toLaurent CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentSeries.coe_algebraMap CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt MvPowerSeries.c_eq_algebraMap CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.C_eq_algebraMap CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.algebraMap_eq CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.algebraMap_pi_self_eq_eval CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.coe_algebraMap_eq_CC CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt PowerSeries.C_eq_algebraMap CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt PowerSeries.algebraMap_eq CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.C_pow CommSemiring => CommMonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentPolynomial.C_eq_algebraMap CommSemiring => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentPolynomial.algebraMap_X_pow CommSemiring => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentPolynomial.algebraMap_eq_toLaurent CommSemiring => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt LaurentSeries.coe_algebraMap CommSemiring => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt MvPowerSeries.c_eq_algebraMap CommSemiring => Units by rfl, simp, aesop, exact?, grind
