/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 10 of 13 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 400000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt csInf_le_csInf' ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_csInf_iff'' ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt notMem_of_lt_csInf' ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt add_inf Lattice => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inf_add Lattice => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inf_div Lattice => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inf_mul Lattice => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inf_sub Lattice => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_inf Lattice => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt add_sup Lattice => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_sup Lattice => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sup_add Lattice => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sup_div Lattice => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sup_mul Lattice => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sup_sub Lattice => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsSelfAdjoint.commute_of_mul_eq_zero NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt commute_lmul_lmul_sq NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt commute_lmul_rmul NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt commute_lmul_rmul_sq NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt commute_lmul_sq_rmul NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt commute_rmul_rmul_sq NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Commute.left_comm Semigroup => Mul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsRightRegular.commute_mul_right_iff Semigroup => Mul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt SemiconjBy.function_semiconj_mul_left Semigroup => Mul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt SemigroupIdeal.coe_closure Semigroup => Mul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt npowRec'_mul_comm Semigroup => Mul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt npowRec'_two_mul Semigroup => Mul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt AddMonoid.minOrder_eq_top AddGroup => AddMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ExponentExists.is_add_torsion AddGroup => AddMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsAddTorsion.exponentExists AddGroup => AddMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithZero.le_exp_of_log_le AddGroup => AddMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithZero.lt_exp_of_log_lt AddGroup => AddMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsRelPrime.of_mul_left_left CommMonoid => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsRelPrime.symm CommMonoid => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ThreeGPFree.eq_right CommMonoid => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt dvd_pow_self_iff CommMonoid => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt one_lt_mul_iff CommMonoid => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sdiff_lt_sdiff_right GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sup_lt_of_lt_sdiff_left GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sup_lt_of_lt_sdiff_right GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt symmDiff_left_comm GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt symmDiff_symmDiff_cancel_left GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.map_add_atTop_eq IsOrderedAddMonoid => AddRightMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NonemptyInterval.length_nonneg IsOrderedAddMonoid => AddRightMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.add_mem_Icc_iff_left IsOrderedAddMonoid => AddRightMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_add_const_Iic IsOrderedAddMonoid => AddRightMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.sub_mem_Icc_iff_left IsOrderedAddMonoid => AddRightMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_nonneg IsStrictOrderedRing => IsOrderedRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Nat.cast_div_le IsStrictOrderedRing => IsOrderedRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Nat.inv_pos_of_nat IsStrictOrderedRing => IsOrderedRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Nat.one_div_cast_pos IsStrictOrderedRing => IsOrderedRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_pow_eq_one IsStrictOrderedRing => IsOrderedRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt DirectedOn.of_linearOrder LinearOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsLowerSet.total LinearOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsUpperSet.total LinearOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Meta.Positivity.nonneg_of_isNNRat LinearOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Meta.Positivity.nonneg_of_isRat LinearOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt AddMonoidHom.associator_eq_zero NonUnitalRing => NonUnitalNonAssocRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt TwoSidedIdeal.mem_span_iff_mem_addSubgroup_closure_absorbing NonUnitalRing => NonUnitalNonAssocRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt TwoSidedIdeal.set_mul_subset NonUnitalRing => NonUnitalNonAssocRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt TwoSidedIdeal.subset_mul_set NonUnitalRing => NonUnitalNonAssocRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt associator_eq_zero NonUnitalRing => NonUnitalNonAssocRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt exists_le_add_iff_le_right AddCommMagma => Add by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt exists_lt_add_iff_lt_right AddCommMagma => Add by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt forall_le_add_iff_le_right AddCommMagma => Add by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt forall_lt_add_iff_lt_right AddCommMagma => Add by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finsupp.add_eq_zero_iff AddCommMonoid => AddMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.FinMeasAdditive.add AddCommMonoid => AddMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt SkewMonoidAlgebra.support_single AddCommMonoid => AddMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ThreeAPFree.eq_right AddCommMonoid => AddMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.Module.NF.sub_eq_eval₁ AddGroup => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt negPart_eq_ite_lt AddGroup => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt posPart_eq_ite_lt AddGroup => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt posPart_eq_of_posPart_pos AddGroup => SubNegMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Submonoid.coe_sup CommMonoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Submonoid.exists_mem_sup CommMonoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Submonoid.forall_mem_sup CommMonoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Submonoid.mem_nhds_one CommMonoid => MulOneClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt DedekindCut.principal_sInf_right CompleteLattice => CompleteSemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsGLB.iInf_eq CompleteLattice => CompleteSemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
