/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 2 of 6 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt bihimp_le_iff_left BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_le_iff_right BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_left_injective BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_left_surjective BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_right_injective BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt bihimp_right_surjective BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt codisjoint_bihimp_sup BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt codisjoint_himp_self_left BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt codisjoint_himp_self_right BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt codisjoint_iff_compl_le_left BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt codisjoint_iff_compl_le_right BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_inf BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt compl_symmDiff_self BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt himp_bihimp_left BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt himp_bihimp_right BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt inf_himp_bihimp BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt ofBoolRing_neg BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt symmDiff_compl_self BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt symmDiff_top BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt top_sdiff BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt top_symmDiff BooleanAlgebra => BooleanRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.sortedGT_sort LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.sortedLT_sort LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.DegLex.single_strictAnti LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.Lex.single_strictAnti LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedGE_insertionSort LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedGE_mergeSort LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedLE_insertionSort LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt List.sortedLE_mergeSort LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt NNRat.Nonneg.coe_ofScientific LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_div LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_inv LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_nnqsmul LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_nnratCast LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_zpow LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.inv_mk LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_div_mk LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_nnqsmul LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_zpow LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.apply_le_of_toColex LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.apply_le_of_toLex LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.toLex_monotone LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Pi.toLex_strictMono LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Positive.coe_inv LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Positive.coe_zpow LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.coe_div LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.coe_zpow LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.normSq_div LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Quaternion.normSq_zpow LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.coe_min LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_min LinearOrder => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.nonneg_op PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.nonneg_unop PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.one_le_op PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.one_le_unop PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.op_le_one PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.op_nonpos PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.unop_le_one PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.unop_nonpos PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.le_def PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.singleton_le_singleton PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.singleton_lt_singleton PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.toColex_le_singleton PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.toColex_le_toColex PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.toColex_sdiff_le_toColex_sdiff PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.bot_eq_zero PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.one_le_op PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.one_le_unop PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_le_one PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_nonneg PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_nonpos PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_le_one PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_nonneg PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_nonpos PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_natCast PartialOrder => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt ExceptT.run_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt ReaderT.run_map Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt ReaderT.run_mapConst Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt ReaderT.run_pure Monad => Applicative by rfl, simp, aesop, exact?, grind
#fh_home_attempt ReaderT.run_seq Monad => Applicative by rfl, simp, aesop, exact?, grind
