/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 19 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Submonoid.exists_mem_sup CommMonoid => MulOneClass by rfl, simp, aesop, exact?
#fh_home_attempt Submonoid.forall_mem_sup CommMonoid => MulOneClass by rfl, simp, aesop, exact?
#fh_home_attempt Submonoid.mem_nhds_one CommMonoid => MulOneClass by rfl, simp, aesop, exact?
#fh_home_attempt DedekindCut.principal_sInf_right CompleteLattice => CompleteSemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt IsGLB.iInf_eq CompleteLattice => CompleteSemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt le_iInf CompleteLattice => CompleteSemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt sInf_eq_of_forall_ge_of_forall_gt_exists_lt CompleteLattice => CompleteSemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt DedekindCut.principal_sSup_left CompleteLattice => CompleteSemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt IsLUB.iSup_eq CompleteLattice => CompleteSemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt iSup_le CompleteLattice => CompleteSemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt sSup_eq_of_forall_le_of_forall_lt_exists_gt CompleteLattice => CompleteSemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt Nucleus.sInf_apply CompleteLattice => SemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt sInf_insert CompleteLattice => SemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt sInf_pair CompleteLattice => SemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt sInf_union CompleteLattice => SemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt iSup₂_eq_top CompleteLinearOrder => CompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt iUnion_Ici_eq_Ici_iInf CompleteLinearOrder => CompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt iUnion_Ici_eq_Ioi_iInf CompleteLinearOrder => CompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt isSaddlePointOn_iff CompleteLinearOrder => CompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Complementeds.coe_inf DistribLattice => Lattice by rfl, simp, aesop, exact?
#fh_home_attempt Complementeds.coe_sup DistribLattice => Lattice by rfl, simp, aesop, exact?
#fh_home_attempt Complementeds.isCompl_coe DistribLattice => Lattice by rfl, simp, aesop, exact?
#fh_home_attempt Finpartition.parts_inf DistribLattice => Lattice by rfl, simp, aesop, exact?
#fh_home_attempt ENat.card_lt_top_of_finite Finite => Top by rfl, simp, aesop, exact?
#fh_home_attempt SimpleGraph.Finsubgraph.coe_top Finite => Top by rfl, simp, aesop, exact?
#fh_home_attempt closure_of_isSwap_of_isPretransitive Finite => Top by rfl, simp, aesop, exact?
#fh_home_attempt isCyclic_iff_exists_orderOf_eq_natCard Finite => Top by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_mul_const_Ici IsOrderedMonoid => MulRightMono by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_mul_const_Iic IsOrderedMonoid => MulRightMono by rfl, simp, aesop, exact?
#fh_home_attempt max_div_div_right' IsOrderedMonoid => MulRightMono by rfl, simp, aesop, exact?
#fh_home_attempt min_div_div_right' IsOrderedMonoid => MulRightMono by rfl, simp, aesop, exact?
#fh_home_attempt abs_mul_sign IsStrictOrderedRing => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt self_mul_sign IsStrictOrderedRing => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt sign_mul_abs IsStrictOrderedRing => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt sign_mul_self IsStrictOrderedRing => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt ReaderT.run_bind Monad => Bind by rfl, simp, aesop, exact?
#fh_home_attempt StateRefT'.lift_bind Monad => Bind by rfl, simp, aesop, exact?
#fh_home_attempt StateT.run_bind Monad => Bind by rfl, simp, aesop, exact?
#fh_home_attempt Std.Iterators.ULiftT.run_bind Monad => Bind by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.bot_mul_bot MulZeroClass => Mul by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.coe_mul MulZeroClass => Mul by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.coe_mul MulZeroClass => Mul by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.top_mul_top MulZeroClass => Mul by rfl, simp, aesop, exact?
#fh_home_attempt Ideal.sup_height_eq_ringKrullDim Nontrivial => Nonempty by rfl, simp, aesop, exact?
#fh_home_attempt MvPolynomial.supDegree_esymm Nontrivial => Nonempty by rfl, simp, aesop, exact?
#fh_home_attempt PrimeSpectrum.subsingleton_iff_isField_of_isReduced Nontrivial => Nonempty by rfl, simp, aesop, exact?
#fh_home_attempt ringKrullDim_nonneg_of_nontrivial Nontrivial => Nonempty by rfl, simp, aesop, exact?
#fh_home_attempt IsOfFinOrder.norm_eq_one NormedRing => SeminormedRing by rfl, simp, aesop, exact?
#fh_home_attempt NormedAlgebra.Complex.exists_norm_sub_smul_one_eq_zero NormedRing => SeminormedRing by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.supNorm_eq_zero_iff NormedRing => SeminormedRing by rfl, simp, aesop, exact?
#fh_home_attempt spectrum.algebraMap_eq_of_mem NormedRing => SeminormedRing by rfl, simp, aesop, exact?
#fh_home_attempt Directed.extend_bot OrderBot => Bot by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.lt_coe_bot OrderBot => Bot by rfl, simp, aesop, exact?
#fh_home_attempt min_eq_bot OrderBot => Bot by rfl, simp, aesop, exact?
#fh_home_attempt min_ne_bot OrderBot => Bot by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.FieldSimp.subst_sub Ring => NonUnitalNonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt TwoSidedIdeal.coe_mop_smul Ring => NonUnitalNonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt TwoSidedIdeal.coe_smul Ring => NonUnitalNonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt UniformSpace.Completion.coe_mul Ring => NonUnitalNonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.AEStronglyMeasurable.nnnorm SeminormedAddCommGroup => SeminormedAddGroup by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.AEStronglyMeasurable.norm SeminormedAddCommGroup => SeminormedAddGroup by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.StronglyMeasurable.nnnorm SeminormedAddCommGroup => SeminormedAddGroup by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.StronglyMeasurable.norm SeminormedAddCommGroup => SeminormedAddGroup by rfl, simp, aesop, exact?
#fh_home_attempt IsSelfAdjoint.div StarRing => StarMul by rfl, simp, aesop, exact?
#fh_home_attempt IsStarProjection.mul StarRing => StarMul by rfl, simp, aesop, exact?
#fh_home_attempt Unitary.coe_neg StarRing => StarMul by rfl, simp, aesop, exact?
#fh_home_attempt Unitary.mem_iff_eq_one_or_eq_neg_one StarRing => StarMul by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Abel.subst_into_addg AddCommGroup => Add by rfl, simp, aesop, exact?
#fh_home_attempt WithLp.ofLp_add AddCommGroup => Add by rfl, simp, aesop, exact?
#fh_home_attempt WithLp.toLp_add AddCommGroup => Add by rfl, simp, aesop, exact?
#fh_home_attempt Complex.coe_smul AddCommGroup => AddCommMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Module.isTorsionFree_int_iff_isAddTorsionFree AddCommGroup => AddCommMonoid by rfl, simp, aesop, exact?
#fh_home_attempt ZModModule.char_nsmul_eq_zero AddCommGroup => AddCommMonoid by rfl, simp, aesop, exact?
#fh_home_attempt WithLp.ofLp_sub AddCommGroup => Sub by rfl, simp, aesop, exact?
#fh_home_attempt WithLp.toLp_sub AddCommGroup => Sub by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_sub AddCommGroup => Sub by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.FinMeasAdditive.neg AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt neg_eq_self_of_addOrderOf_eq_two AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt neg_eq_self_of_exponent_two AddGroup => SubtractionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.GradedObject.hom_ext CategoryTheory.Category => Quiver by rfl, simp, aesop, exact?
