/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 14 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Subtype.nndist_eq PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt ULift.nndist_eq PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt ULift.nndist_up_up PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt nndist_ofAdd PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt nndist_ofDual PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt nndist_ofMul PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt nndist_toAdd PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt nndist_toDual PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt nndist_toMul PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt div_le_one Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt div_lt_one Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt inv_strictAntiOn Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt le_div_self Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt le_one_div Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt lt_one_div Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt monotone_div_right_of_nonneg Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt one_div_le Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt one_div_le_one_div_of_le Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt one_div_lt Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt one_le_div Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt one_lt_div Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt strictMono_div_right_of_pos Semifield => GroupWithZero by rfl, simp, aesop, exact?
#fh_home_attempt SemiconjBy.zpow_right Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Set.smul_inter_nonempty_iff' Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt leOnePart_eq_inv Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt leOnePart_eq_ite Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt leOnePart_eq_ite_lt Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt leOnePart_eq_one Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt leOnePart_le_one Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt mul_zpow_mul Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt oneLePart_eq_ite_lt Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt oneLePart_of_one_lt_oneLePart Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt pow_intGCD_eq_one Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt pow_natAbs_eq_one Group => DivInvMonoid by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.edist_op PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.edist_unop PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt Metric.pos_of_mem_eball PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.edist_op PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.edist_unop PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt Subtype.edist_eq PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt Subtype.edist_mk_mk PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt Subtype.preimage_eball PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt ULift.edist_eq PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt ULift.edist_up_up PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt UniformFun.edist_def PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt UniformFun.edist_le PseudoEMetricSpace => EDist by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Linarith.mul_zero_eq Semiring => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Linarith.zero_mul_eq Semiring => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt mul_nonneg_iff_of_pos_left Semiring => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt mul_nonneg_iff_of_pos_right Semiring => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt nonneg_and_nonneg_or_nonpos_and_nonpos_of_mul_nonneg Semiring => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt nonneg_of_mul_nonneg_left Semiring => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt nonneg_of_mul_nonneg_right Semiring => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt nonpos_of_mul_nonneg_left Semiring => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt nonpos_of_mul_nonneg_right Semiring => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt nonpos_of_mul_nonpos_left Semiring => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt nonpos_of_mul_nonpos_right Semiring => MulZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.coe_normUnit CommRing => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.degree_eq_degree_of_associated CommRing => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.isUnit_C_add_X_mul_iff CommRing => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.splits_X_mul CommRing => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.splits_mul' CommRing => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.splits_mul_iff_left CommRing => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.splits_mul_iff_right CommRing => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.units_coeff_zero_smul CommRing => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt QuaternionAlgebra.coe_pow CommRing => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt ValuationRing.unique_irreducible CommRing => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Finset.inv_op_smul_finset_distrib Group => DivisionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Finset.inv_smul_finset_distrib Group => DivisionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Finset.small_pow_of_small_tripling Group => DivisionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Set.inv_op_smul_set_distrib Group => DivisionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Set.inv_smul_set_distrib Group => DivisionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Set.mem_smul_set_inv Group => DivisionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt SimpleGraph.mulCayley_inv Group => DivisionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt inv_eq_self_of_exponent_two Group => DivisionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt inv_eq_self_of_orderOf_eq_two Group => DivisionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt max_one_div_max_inv_one_eq_self Group => DivisionMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_div_Ici IsOrderedMonoid => MulLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_div_Iic IsOrderedMonoid => MulLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_mul_Ici IsOrderedMonoid => MulLeftMono by rfl, simp, aesop, exact?
