/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 5 of 13 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 400000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt StrictMono.id_le LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt denselyOrdered_set_iff_subsingleton LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt dirSupClosedOn_iff_of_linearOrder LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt dirSupClosed_iff_of_linearOrder LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt dirSupInaccOn_iff_of_linearOrder LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt dirSupInacc_iff_of_linearOrder LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt exists_lub_Iio LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt exists_square_le LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt iInter_Iic_eq_empty_iff LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt iUnion_Iio_eq_univ_iff LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_le_one_iff₀ LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_le_self_iff LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_lt_one_iff₀ LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_neg'' LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_nonpos LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isCofinal_of_isCofinal_sUnion LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt lt_isLUB_iff LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt maximal_iff_isGreatest LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt minimal_iff_isLeast LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mulPosMono_iff_mulPosReflectLT LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mulPosStrictMono_iff_mulPosReflectLE LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_nonneg_iff_of_pos_left LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_nonneg_iff_of_pos_right LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt noBotOrder_iff_noMinOrder LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt noTopOrder_iff_noMaxOrder LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt northcott_iff_tendsto LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt one_le_pow_iff_of_nonneg LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt posMulMono_iff_posMulReflectLT LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt posMulStrictMono_iff_posMulReflectLE LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt pos_of_left_mul_lt_le LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt pos_of_right_mul_lt_le LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt pow_le_one_iff_of_nonneg LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sq_eq_sq₀ LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Asymptotics.IsEquivalent.add_isLittleO NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Asymptotics.IsEquivalent.comp_tendsto NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Asymptotics.IsEquivalent.congr_left NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Asymptotics.IsEquivalent.isBigO NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Asymptotics.IsEquivalent.mono NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ConvexOn.isBoundedUnder_abs NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt EisensteinSeries.isLittleO_const_left_of_properSpace_of_discreteTopology NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt EisensteinSeries.summable_of_isBigO_rpow_norm NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.HasFiniteIntegral.norm NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.Lp.ae_tendsto_of_cauchy_eLpNorm' NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.integrable_norm_iff NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.tendstoInMeasure_of_tendsto_eLpNorm NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.diam_sphere_eq NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.isPathConnected_ball NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.isPathConnected_closedBall NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.isPathConnected_eball NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.isPreconnected_ball NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.isPreconnected_closedBall NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.isPreconnected_closedEBall NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Metric.isPreconnected_eball NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Monotone.cauchySeq_series_mul_of_tendsto_zero_of_bounded NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt PhragmenLindelof.isBigO_sub_exp_exp NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt PhragmenLindelof.isBigO_sub_exp_rpow NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt StrictConvex.extremePoints_eq_sdiff_interior NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt affinity_unitBall NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ampleSet_univ NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isBigO_norm_Icc_restrict_atTop NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isBigO_rpow_top_log_smul NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isBigO_rpow_zero_log_smul NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isNonneg_inner NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isSymm_inner NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_gauge_of_subset_closedBall NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mem_posTangentConeAt_of_frequently_mem NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt neg_one_le_real_inner_of_norm_eq_one NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt norm_eq_iInf_iff_real_inner_le_zero NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt posTangentConeAt_mono NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt real_inner_le_one_of_norm_eq_one NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt real_linearMap_map_smul_complex NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sphere_ext_iff NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sub_mem_posTangentConeAt_of_segment_subset NormedAddCommGroup => SeminormedAddCommGroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.isBoundedUnder_le_abs LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_abs_atBot_atTop LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_mabs_atBot_atTop LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.abs_sum_le_sum_abs LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.abs_sum_of_nonneg LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.abs_sum_of_nonneg' LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Meta.NormNum.isNNRat_abs_neg LinearOrder => Lattice by norm_num, omega, positivity, order, nlinarith, grind
