/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 17 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Topology.WithLower.isOpen_def Preorder => TopologicalSpace by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithLower.isOpen_preimage_ofLower Preorder => TopologicalSpace by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithUpper.isOpen_def Preorder => TopologicalSpace by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithUpper.isOpen_preimage_ofUpper Preorder => TopologicalSpace by rfl, simp, aesop, exact?
#fh_home_attempt AddCircle.coe_add AddCommGroup => AddGroup by rfl, simp, aesop, exact?
#fh_home_attempt AddCircle.coe_eq_zero_iff AddCommGroup => AddGroup by rfl, simp, aesop, exact?
#fh_home_attempt AddCircle.coe_neg AddCommGroup => AddGroup by rfl, simp, aesop, exact?
#fh_home_attempt AddCircle.coe_period AddCommGroup => AddGroup by rfl, simp, aesop, exact?
#fh_home_attempt Function.Periodic.const_sub AddCommGroup => AddGroup by rfl, simp, aesop, exact?
#fh_home_attempt SkewMonoidAlgebra.support_neg AddCommGroup => AddGroup by rfl, simp, aesop, exact?
#fh_home_attempt AddMonoid.minOrder_eq_top AddGroup => AddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt ExponentExists.is_add_torsion AddGroup => AddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt IsAddTorsion.exponentExists AddGroup => AddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Matrix.conjTranspose_zsmul AddGroup => AddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.le_exp_of_log_le AddGroup => AddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.lt_exp_of_log_lt AddGroup => AddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.isGLB_sInf ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt ciInf_le' ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt csInf_le' ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt csInf_le_csInf' ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt le_csInf_iff'' ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt notMem_of_lt_csInf' ConditionallyCompleteLinearOrderBot => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt IsUnit.neg HasDistribNeg => Neg by rfl, simp, aesop, exact?
#fh_home_attempt SemiconjBy.neg_one_left HasDistribNeg => Neg by rfl, simp, aesop, exact?
#fh_home_attempt SemiconjBy.neg_one_right HasDistribNeg => Neg by rfl, simp, aesop, exact?
#fh_home_attempt Units.coe_neg_one HasDistribNeg => Neg by rfl, simp, aesop, exact?
#fh_home_attempt Units.val_neg HasDistribNeg => Neg by rfl, simp, aesop, exact?
#fh_home_attempt neg_one_pow_eq_or HasDistribNeg => Neg by rfl, simp, aesop, exact?
#fh_home_attempt add_inf Lattice => SemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt inf_add Lattice => SemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt inf_div Lattice => SemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt inf_mul Lattice => SemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt inf_sub Lattice => SemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt mul_inf Lattice => SemilatticeInf by rfl, simp, aesop, exact?
#fh_home_attempt add_sup Lattice => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt mul_sup Lattice => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt sup_add Lattice => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt sup_div Lattice => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt sup_mul Lattice => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt sup_sub Lattice => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt ContractingWith.dist_le_mul MetricSpace => EMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt ContractingWith.fixedPoint_unique' MetricSpace => EMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt ContractingWith.one_sub_K_pos MetricSpace => EMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt Metric.IsCover.isCompact MetricSpace => EMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt Metric.exists_continuous_nnreal_forall_closedBall_subset MetricSpace => EMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt Perfect.small_diam_splitting MetricSpace => EMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt Finset.noncommProd_lemma Monoid => Mul by rfl, simp, aesop, exact?
#fh_home_attempt MulAut.smul_def Monoid => Mul by rfl, simp, aesop, exact?
#fh_home_attempt Set.Ici_mul_Ici_eq Monoid => Mul by rfl, simp, aesop, exact?
#fh_home_attempt isAddRegular_ofMul Monoid => Mul by rfl, simp, aesop, exact?
#fh_home_attempt isRegular_toMul Monoid => Mul by rfl, simp, aesop, exact?
#fh_home_attempt min_mul_distrib Monoid => Mul by rfl, simp, aesop, exact?
#fh_home_attempt IsSelfAdjoint.commute_of_mul_eq_zero NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt commute_lmul_lmul_sq NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt commute_lmul_rmul NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt commute_lmul_rmul_sq NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt commute_lmul_sq_rmul NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt commute_rmul_rmul_sq NonUnitalNonAssocRing => NonUnitalNonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt Commute.left_comm Semigroup => Mul by rfl, simp, aesop, exact?
#fh_home_attempt IsRightRegular.commute_mul_right_iff Semigroup => Mul by rfl, simp, aesop, exact?
#fh_home_attempt SemiconjBy.function_semiconj_mul_left Semigroup => Mul by rfl, simp, aesop, exact?
#fh_home_attempt SemigroupIdeal.coe_closure Semigroup => Mul by rfl, simp, aesop, exact?
#fh_home_attempt npowRec'_mul_comm Semigroup => Mul by rfl, simp, aesop, exact?
#fh_home_attempt npowRec'_two_mul Semigroup => Mul by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.inf_apply SemilatticeInf => Min by rfl, simp, aesop, exact?
#fh_home_attempt Subtype.coe_inf SemilatticeInf => Min by rfl, simp, aesop, exact?
#fh_home_attempt Subtype.mk_inf_mk SemilatticeInf => Min by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.coe_inf SemilatticeInf => Min by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.coe_inf SemilatticeInf => Min by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.coe_inf SemilatticeInf => Min by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.sup_apply SemilatticeSup => Max by rfl, simp, aesop, exact?
#fh_home_attempt Subtype.coe_sup SemilatticeSup => Max by rfl, simp, aesop, exact?
#fh_home_attempt Subtype.mk_sup_mk SemilatticeSup => Max by rfl, simp, aesop, exact?
#fh_home_attempt WithBot.coe_sup SemilatticeSup => Max by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.coe_sup SemilatticeSup => Max by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.coe_sup SemilatticeSup => Max by rfl, simp, aesop, exact?
#fh_home_attempt ArithmeticFunction.coe_zeta_mul_comm Semiring => NonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt ArithmeticFunction.natCoe_mul Semiring => NonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt CharTwo.add_self_eq_zero Semiring => NonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Meta.NormNum.isNat_mul Semiring => NonAssocSemiring by rfl, simp, aesop, exact?
