/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 18 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt add_le_mul_of_left_le_right Semiring => NonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt add_le_mul_of_right_le_left Semiring => NonAssocSemiring by rfl, simp, aesop, exact?
#fh_home_attempt AddEquiv.strictMono_subsemigroupCongr AddCommMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Abel.subst_into_add AddCommMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt Set.AddAntidiagonal.fst_eq_fst_iff_snd_eq_snd AddCommMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt ofDegLex_add AddCommMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt toDegLex_add AddCommMonoid => Add by rfl, simp, aesop, exact?
#fh_home_attempt Finset.HasAntidiagonal.antidiagonal.fst_le AddCommMonoid => AddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.add_eq_zero_iff AddCommMonoid => AddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.FinMeasAdditive.add AddCommMonoid => AddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt SkewMonoidAlgebra.support_single AddCommMonoid => AddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt ThreeAPFree.eq_right AddCommMonoid => AddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.op_nsmul AddMonoid => SMul by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.unop_nsmul AddMonoid => SMul by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.coe_nsmul AddMonoid => SMul by rfl, simp, aesop, exact?
#fh_home_attempt mul_nsmul AddMonoid => SMul by rfl, simp, aesop, exact?
#fh_home_attempt nsmul_iterate AddMonoid => SMul by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Algebra.isNat_zero_eq CommSemiring => AddMonoidWithOne by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.Common.inv_add CommSemiring => AddMonoidWithOne by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.cast_pos CommSemiring => AddMonoidWithOne by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.cast_zero CommSemiring => AddMonoidWithOne by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.natCast_add CommSemiring => AddMonoidWithOne by rfl, simp, aesop, exact?
#fh_home_attempt Finset.compl_union Fintype => HeytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.inter_compl Fintype => HeytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.subset_compl_comm Fintype => HeytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.subset_compl_iff_disjoint_left Fintype => HeytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt Finset.subset_compl_iff_disjoint_right Fintype => HeytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt sdiff_lt_sdiff_right GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt sup_lt_of_lt_sdiff_left GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt sup_lt_of_lt_sdiff_right GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt symmDiff_left_comm GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt symmDiff_symmDiff_cancel_left GeneralizedBooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?
#fh_home_attempt ArchimedeanClass.mk_mul IsStrictOrderedRing => IsOrderedAddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt ArchimedeanClass.mk_one IsStrictOrderedRing => IsOrderedAddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt ArchimedeanClass.mk_pow IsStrictOrderedRing => IsOrderedAddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt CauSeq.rat_inf_continuous_lemma IsStrictOrderedRing => IsOrderedAddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt CauSeq.rat_sup_continuous_lemma IsStrictOrderedRing => IsOrderedAddMonoid by rfl, simp, aesop, exact?
#fh_home_attempt DirectedOn.of_linearOrder LinearOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsLowerSet.total LinearOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt IsUpperSet.total LinearOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Meta.Positivity.nonneg_of_isNNRat LinearOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Meta.Positivity.nonneg_of_isRat LinearOrder => LE by rfl, simp, aesop, exact?
#fh_home_attempt ReaderT.run_map Monad => Functor by rfl, simp, aesop, exact?
#fh_home_attempt ReaderT.run_mapConst Monad => Functor by rfl, simp, aesop, exact?
#fh_home_attempt SatisfiesM_ReaderT_eq Monad => Functor by rfl, simp, aesop, exact?
#fh_home_attempt StateT.map_const Monad => Functor by rfl, simp, aesop, exact?
#fh_home_attempt WriterT.run_map Monad => Functor by rfl, simp, aesop, exact?
#fh_home_attempt AddMonoidHom.associator_eq_zero NonUnitalRing => NonUnitalNonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt TwoSidedIdeal.mem_span_iff_mem_addSubgroup_closure_absorbing NonUnitalRing => NonUnitalNonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt TwoSidedIdeal.set_mul_subset NonUnitalRing => NonUnitalNonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt TwoSidedIdeal.subset_mul_set NonUnitalRing => NonUnitalNonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt associator_eq_zero NonUnitalRing => NonUnitalNonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt ArithmeticFunction.intCoe_mul Ring => NonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt CharP.prime_ringChar Ring => NonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt IsSelfAdjoint.intCast Ring => NonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt RingCon.range_mk' Ring => NonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt Subring.sum_mem Ring => NonAssocRing by rfl, simp, aesop, exact?
#fh_home_attempt CategoryTheory.Mat.add_apply Ring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.ofFinsupp_zsmul Ring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.toFinsupp_zsmul Ring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt ZMod.algebraOfModule.proof Ring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt uniq_inv_of_isField Ring => Semiring by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Linarith.eq_of_eq_of_eq Semiring => AddZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Linarith.le_of_eq_of_le Semiring => AddZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Linarith.le_of_le_of_eq Semiring => AddZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Linarith.lt_of_eq_of_lt Semiring => AddZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Linarith.lt_of_lt_of_eq Semiring => AddZeroClass by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Abel.subst_into_negg AddCommGroup => Neg by rfl, simp, aesop, exact?
#fh_home_attempt WithLp.ofLp_neg AddCommGroup => Neg by rfl, simp, aesop, exact?
#fh_home_attempt WithLp.toLp_neg AddCommGroup => Neg by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.LinearOrderedAddCommGroup.coe_neg AddCommGroup => Neg by rfl, simp, aesop, exact?
#fh_home_attempt exists_le_add_iff_le_right AddCommMagma => Add by rfl, simp, aesop, exact?
#fh_home_attempt exists_lt_add_iff_lt_right AddCommMagma => Add by rfl, simp, aesop, exact?
#fh_home_attempt forall_le_add_iff_le_right AddCommMagma => Add by rfl, simp, aesop, exact?
#fh_home_attempt forall_lt_add_iff_lt_right AddCommMagma => Add by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Module.NF.sub_eq_eval₁ AddGroup => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt negPart_eq_ite_lt AddGroup => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt posPart_eq_ite_lt AddGroup => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt posPart_eq_of_posPart_pos AddGroup => SubNegMonoid by rfl, simp, aesop, exact?
#fh_home_attempt Submonoid.coe_sup CommMonoid => MulOneClass by rfl, simp, aesop, exact?
