/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 4 of 20 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt AddOpposite.one_le_op PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.one_le_unop PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.op_le_one PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.op_nonpos PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.unop_le_one PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.unop_nonpos PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.forall_le_mono PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.forall_lt_mono PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.le_def PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.le_iff_sdiff_subset_lowerClosure PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.singleton_le_singleton PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.singleton_le_toColex PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.singleton_lt_singleton PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.toColex_le_singleton PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.toColex_le_toColex PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.toColex_mono PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.Colex.toColex_sdiff_le_toColex_sdiff PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.bot_eq_zero PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Interval.inv_bot PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Interval.neg_bot PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MeasureTheory.VectorMeasure.le_iff' PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MeasureTheory.VectorMeasure.restrict_le_zero_of_not_measurable PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MeasureTheory.VectorMeasure.zero_le_restrict_not_measurable PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.one_le_op PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.one_le_unop PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_le_one PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_nonneg PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_nonpos PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_le_one PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_nonneg PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_nonpos PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.coe_inv_interval PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.coe_neg_interval PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_inv PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_neg PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.inv_pure PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.neg_pure PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_inv PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_neg PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_natCast PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.Icc_bot_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.Icc_coe_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.Ico_bot_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.Ico_coe_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.Ioc_bot_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.Ioc_coe_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.Ioo_bot_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.Ioo_coe_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.Icc_coe_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.Icc_coe_top PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.Ico_coe_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.Ico_coe_top PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.Ioc_coe_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.Ioc_coe_top PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.Ioo_coe_coe PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.Ioo_coe_top PartialOrder => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.op_le_op Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.unop_le_unop Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddUnits.val_le_val Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddUnits.val_lt_val Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.coe_lt_coe Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Interval.bot_div Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Interval.div_bot Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt Interval.dual_top Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_le_op Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_le_unop Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.coe_div_interval Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.coe_one_interval Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.coe_top_interval Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.coe_zero_interval Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.dual_top Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_div Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_natCast Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_nsmul Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_one Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_pow Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.fst_zero Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_div Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_natCast Preorder => Ord by rfl, simp, aesop, exact?, grind
#fh_home_attempt NonemptyInterval.snd_nsmul Preorder => Ord by rfl, simp, aesop, exact?, grind
