/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 13 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt abs_sub IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt abs_sub_le IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt zsmul_left_mono IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt Associates.associated_map_mk CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Associates.decompositionMonoid_iff CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Associates.isPrimal_mk CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Associates.mk_dvd_mk CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Associates.mk_isRelPrime_iff CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Associates.mk_mul_mk CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Finset.HasMulAntidiagonal.mulAntidiagonal.fst_le CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt IsRelPrime.isUnit_of_dvd CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt IsRelPrime.of_mul_left_left CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt IsRelPrime.symm CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt ThreeGPFree.eq_right CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt Units.smul_eq_mul CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt dvd_pow_self_iff CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt emultiplicity_mk_eq_emultiplicity CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt one_lt_mul_iff CommMonoid => Monoid by rfl, simp, aesop, exact?
#fh_home_attempt ArchimedeanClass.exists_nat_ge_of_mk_nonneg CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt Ideal.is_fg_degreeLE CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt IsBezout.gcd_eq_sum CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Tactic.Ring.intCast_mul CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.add_modByMonic CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.exists_multiset_roots CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.le_rootMultiplicity_iff CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.leadingCoeff_divByMonic_of_monic CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.modByMonic_eq_of_dvd_sub CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.rootMultiplicity_eq_zero_iff CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.smul_modByMonic CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt Quaternion.re_mul CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt Ring.ord_mul_of_isUnit_left CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt abs_pow_sub_pow_le CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt abs_unit_intCast CommRing => Ring by rfl, simp, aesop, exact?
#fh_home_attempt GenContFract.succ_nth_conv_eq_squashGCF_nth_conv Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt Mathlib.Meta.NormNum.IsRat.natCeil Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt OnePoint.equivProjectivization_smul Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt Rat.cast_lt_zero Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt Rat.cast_nonneg Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt Rat.cast_nonpos Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt Rat.cast_pos Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt Rat.cast_pos_of_pos Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt Subfield.algebraMap_ofSubfield Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt Subfield.bot_eq_of_charZero Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt Subfield.mem_closure_iff Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt exists_rat_lt Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt geom_sum_Ico_le_of_lt_one Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt pow_div_pow_eventuallyEq_atBot Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt pow_div_pow_eventuallyEq_atTop Field => DivisionRing by rfl, simp, aesop, exact?
#fh_home_attempt Filter.bliminf_antitone CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.bliminf_antitone_filter CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.blimsup_congr' CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.blimsup_mono CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.blimsup_monotone_filter CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.liminf_le_of_frequently_le' CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.limsInf_bot CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.limsInf_top CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.limsSup_bot CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.limsSup_top CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.limsup_const_bot CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.limsup_eq_sInf_sSup CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.mono_bliminf' CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt Filter.mono_blimsup' CompleteLattice => ConditionallyCompleteLattice by rfl, simp, aesop, exact?
#fh_home_attempt AlgebraicGeometry.Scheme.SpecToEquivOfField_eq_iff Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt AlgebraicGeometry.pullback_of_geometrically Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt AlgebraicGeometry.pullback_of_geometrically' Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt MonomialOrder.sPolynomial_decomposition' Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt NumberField.RingOfIntegers.coe_mk Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt NumberField.RingOfIntegers.mk_add_mk Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt NumberField.RingOfIntegers.mk_eq_mk Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt NumberField.RingOfIntegers.mk_mul_mk Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt NumberField.RingOfIntegers.mk_sub_mk Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.X_sub_C_dvd_derivative_of_X_sub_C_dvd_divByMonic Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt WeierstrassCurve.Jacobian.Point.add_point Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt WeierstrassCurve.Jacobian.Point.neg_point Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt WeierstrassCurve.Projective.Point.add_point Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt WeierstrassCurve.Projective.Point.neg_point Field => CommRing by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.nndist_op PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt AddOpposite.nndist_unop PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.nndist_op PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
#fh_home_attempt MulOpposite.nndist_unop PseudoMetricSpace => NNDist by rfl, simp, aesop, exact?
