/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 15 of 20 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt ArchimedeanClass.mk_mul IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArchimedeanClass.mk_one IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt ArchimedeanClass.mk_pow IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Int.cast_one_le_of_pos IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt div_lt_one_iff IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt max_div_div_right IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt min_div_div_right IsStrictOrderedRing => IsOrderedRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLawson.isClosed_preimage_ofLawson Preorder => UniformSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLawson.isOpen_def Preorder => UniformSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLawson.isOpen_preimage_ofLawson Preorder => UniformSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.isOpen_def Preorder => UniformSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.isOpen_preimage_ofLower Preorder => UniformSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.isOpen_def Preorder => UniformSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.isOpen_preimage_ofUpper Preorder => UniformSpace by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLawson.isClosed_preimage_ofLawson Preorder => UniformSpace.Core by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLawson.isOpen_def Preorder => UniformSpace.Core by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLawson.isOpen_preimage_ofLawson Preorder => UniformSpace.Core by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.isOpen_def Preorder => UniformSpace.Core by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithLower.isOpen_preimage_ofLower Preorder => UniformSpace.Core by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.isOpen_def Preorder => UniformSpace.Core by rfl, simp, aesop, exact?, grind
#fh_home_attempt Topology.WithUpper.isOpen_preimage_ofUpper Preorder => UniformSpace.Core by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.inf_apply SemilatticeInf => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Fintype.toOrderBot.congr_simp SemilatticeInf => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.coe_inf SemilatticeInf => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.mk_inf_mk SemilatticeInf => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.coe_inf SemilatticeInf => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_inf SemilatticeInf => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithZero.coe_inf SemilatticeInf => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.inf_apply SemilatticeInf => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Fintype.toOrderBot.congr_simp SemilatticeInf => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.coe_inf SemilatticeInf => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.mk_inf_mk SemilatticeInf => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.coe_inf SemilatticeInf => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_inf SemilatticeInf => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithZero.coe_inf SemilatticeInf => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.inf_apply SemilatticeInf => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Fintype.toOrderBot.congr_simp SemilatticeInf => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.coe_inf SemilatticeInf => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.mk_inf_mk SemilatticeInf => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.coe_inf SemilatticeInf => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_inf SemilatticeInf => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithZero.coe_inf SemilatticeInf => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt IsUnit.neg HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt SemiconjBy.neg_one_left HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt SemiconjBy.neg_one_right HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt Units.coe_neg_one HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt Units.val_neg HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt neg_one_pow_eq_or HasDistribNeg => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.inf_apply SemilatticeInf => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.coe_inf SemilatticeInf => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.mk_inf_mk SemilatticeInf => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.coe_inf SemilatticeInf => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_inf SemilatticeInf => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithZero.coe_inf SemilatticeInf => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.sup_apply SemilatticeSup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.coe_sup SemilatticeSup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.mk_sup_mk SemilatticeSup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.coe_sup SemilatticeSup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_sup SemilatticeSup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithZero.coe_sup SemilatticeSup => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.sup_apply SemilatticeSup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.coe_sup SemilatticeSup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.mk_sup_mk SemilatticeSup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.coe_sup SemilatticeSup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_sup SemilatticeSup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithZero.coe_sup SemilatticeSup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.sup_apply SemilatticeSup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.coe_sup SemilatticeSup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.mk_sup_mk SemilatticeSup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.coe_sup SemilatticeSup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_sup SemilatticeSup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithZero.coe_sup SemilatticeSup => Units by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.sup_apply SemilatticeSup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.coe_sup SemilatticeSup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt Subtype.mk_sup_mk SemilatticeSup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithBot.coe_sup SemilatticeSup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithTop.coe_sup SemilatticeSup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithZero.coe_sup SemilatticeSup => Vector by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddMonoid.End.zero_apply AddCommMonoid => AddAction by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finset.HasAntidiagonal.antidiagonal.fst_le AddCommMonoid => AddAction by rfl, simp, aesop, exact?, grind
