/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 2 of 13 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 400000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt bot_covBy_iff PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt countableSupClosure_singleton PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt covBy_iff_atom_Ici PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt covBy_iff_coatom_Iic PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt eventuallyEq_of_isMinFilter_of_isMaxFilter PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt exists_covBy_seq_of_wellFoundedLT_wellFoundedGT_of_le PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt finprod_le_finprod PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt finprod_le_finprod' PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt finsum_le_finsum' PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_mul_le_iff₀ PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_mul_lt_iff₀ PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_nonneg PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_pos PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isUpperSet_iff_Ioi_subset PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_inv_mul_iff₀ PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_mul_inv_iff₀ PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt lt_inv_mul_iff₀ PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt lt_mul_inv_iff₀ PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mulPosMono_iff_mulPosStrictMono PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mulPosReflectLE_iff_mulPosReflectLT PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_add_mul_le_mul_add_mul PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_add_mul_lt_mul_add_mul PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_eq_mul_iff_eq_and_eq_of_pos PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_eq_mul_iff_eq_and_eq_of_pos' PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_inv_le_iff₀ PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_inv_lt_iff₀ PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_lt_mul_of_neg_left PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_lt_mul_of_neg_right PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt posMulMono_iff_posMulStrictMono PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt posMulReflectLE_iff_posMulReflectLT PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt pow_pos PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt pow_succ_pos PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sq_pos_of_pos PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt strictMono_mul_left_of_pos PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt wcovBy_eq_reflGen_covBy PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt zpow_left_mono PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt zpow_left_monoOn₀ PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt zpow_right_mono PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt zsmul_left_mono PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt zsmul_mono_right PartialOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.Tendsto.atTop_zsmul_const LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_const_mul_pow_atBot_iff LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_div_const_atBot_of_neg LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_div_const_atBot_of_pos LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_div_const_atTop_of_neg LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.tendsto_zpow_atTop_atTop LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt GenContFract.convs_eq_convs' LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Int.cast_le_neg_one_of_neg LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Int.cast_one_le_of_pos LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsGLB.biUnion_Ici_eq_Ici LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt LinearOrderedField.smul_Icc LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt LinearOrderedField.smul_Ici LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt LinearOrderedField.smul_Ico LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt LinearOrderedField.smul_Iic LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt LinearOrderedField.smul_Iio LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt LinearOrderedField.smul_Ioc LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt LinearOrderedField.smul_Ioi LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt LinearOrderedField.smul_Ioo LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.IsChain.cons_of_le LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.cons_le_cons LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Meta.NormNum.IsInt.natCeil LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Meta.NormNum.IsRat.natCeil LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.CancelDenoms.cancel_factors_le LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.CancelDenoms.cancel_factors_lt LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.LinearCombination.div_le_const LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.LinearCombination.div_lt_const LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.LinearCombination.div_lt_const_weak LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.IsStoppingTime.measurableSet_eq_of_countable_range' LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.VectorMeasure.exists_pos_measure_of_not_restrict_le_zero LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_le_one LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_lt_one LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_lt_zero LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_nonneg LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_nonpos LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_pos LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.cast_strictMono LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.not_cast_lt_zero LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.one_le_cast LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt NNRat.one_lt_cast LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Nat.cast_div_le LinearOrder => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
