/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 13 of 13 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 400000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Finset.isUnit_coe DivisionMonoid => Monoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt UniqueDiffWithinAt.pi DivisionSemiring => Semiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt edist_pos EMetricSpace => EDist by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MonomialOrder.isUnit_leadingCoeff Field => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.CancelDenoms.div_subst Field => DivisionCommMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Submonoid.orderOf_le_card Group => LeftCancelMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Unitary.coe_inv GroupWithZero => DivisionMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt gcd_dvd_iff_exists IsBezout => GCDMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Associates.FactorSet.prod_eq_zero_iff IsCancelMulZero => NoZeroDivisors by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_mul_const_Iic IsOrderedMonoid => MulRightMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Nat.zero_le_self_sub_floor IsStrictOrderedRing => AddRightMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt UniformSpace.Completion.coe_mul IsTopologicalRing => ContinuousMul by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Lean.Grind.CommRing.Poly.normEq0_eq Lean.Grind.CommRing => Lean.Grind.Ring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Lean.Order.chain_conj Lean.Order.CCPO => Lean.Order.PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Meta.Positivity.max_ne LinearOrder => Max by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Meta.Positivity.min_ne LinearOrder => Min by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt ProbabilityTheory.withDensity_preCDF MeasureTheory.IsFiniteMeasure => MeasureTheory.SigmaFinite by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt hofer MetricSpace => PseudoMetricSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Balanced.starConvex Module => SMulWithZero by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt FreeMonoid.hom_eq Monoid => MulOne by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.noncommProd_mul_distrib_aux Monoid => Semigroup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt noZeroDivisors_tfae NonUnitalNonAssocRing => MulZeroClass by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt AddMonoidHom.mulLeft₃_eq_mulRight₃ NonUnitalSemiring => NonUnitalNonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Continuous.sigmoid NormedAddCommGroup => TopologicalSpace by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt spectrum.algebraMap_eq_of_mem NormedAlgebra => Algebra by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Bornology.isVonNBounded_pi_iff NormedDivisionRing => SeminormedRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sup_sInf_eq Order.Coframe => CompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Nucleus.map_himp_le Order.Frame => GeneralizedHeytingAlgebra by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Nucleus.comp_eq_right_iff_le Order.Frame => SemilatticeInf by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt summable_pow_div_add RCLike => NormedDivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Memℓp.bilin_of_zero_left RCLike => NormedField by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt not_ringChar_dvd_of_invertible Ring => NonAssocSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.FieldSimp.subst_sub Ring => NonUnitalNonAssocRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt SSet.Subcomplex.Pairing.strongInnerAnodyneExtensions SSet.Subcomplex.Pairing.IsRegular => SSet.Subcomplex.Pairing.IsProper by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.Ring.Common.div_pf Semifield => DivInvMonoid by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.PairwiseDisjoint.attach SemilatticeInf => PartialOrder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt eventually_ne_of_tendsto_norm_atTop SeminormedAddGroup => Norm by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt eventually_ne_of_tendsto_norm_atTop' SeminormedGroup => Norm by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Asymptotics.isBigOWith_of_eq_mul SeminormedRing => NonUnitalSeminormedRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Tactic.FieldSimp.subst_add Semiring => Distrib by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.le_total Std.Asymm => Std.Total by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Matrix.IsDiag.sub SubtractionMonoid => SubNegZeroMonoid by norm_num, omega, positivity, order, nlinarith, grind
