/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import FerrisHoward.Atlas.Home

/-!
# Attempt shard 12 of 23 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt MvPolynomial.isNilpotent_iff CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt MvPolynomial.prime_C_iff CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt MvPolynomial.toMvPowerSeries_isUniformInducing CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt MvPolynomial.vars_C_mul CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.IsMonicOfDegree.aeval_add CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.Monic.mem_nonZeroDivisors CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.mem_nonZeroDivisors_of_leadingCoeff CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.mem_nonZeroDivisors_of_trailingCoeff CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.prime_C_iff CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt Polynomial.toPowerSeries_toMvPowerSeries CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt PowerSeries.derivative.ext CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt PowerSeries.rescale_injective CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt QuadraticAlgebra.algebraMap_mem_nonZeroDivisors_iff CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt QuaternionAlgebra.coe_commutes CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt QuaternionAlgebra.coe_mul_eq_smul CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt monomial_mem_adjoin_monomial CommRing => CommSemiring by rfl, simp, aesop, exact?
#fh_home_attempt Metric.closedEBall_zero EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt Metric.ediam_pos_iff EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt Metric.ediam_pos_iff' EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt Metric.eventually_nhds_zero_forall_closedEBall_subset EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt Metric.isSeparated_zero EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt Metric.packingNumber_zero EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt TopologicalSpace.Closeds.continuous_infEDist EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt TopologicalSpace.Closeds.edist_eq EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt TopologicalSpace.Closeds.lipschitz_sup EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt TopologicalSpace.Compacts.edist_eq EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt TopologicalSpace.Compacts.isometry_singleton EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt TopologicalSpace.Compacts.lipschitz_sup EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt TopologicalSpace.NonemptyCompacts.isometry_singleton EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt TopologicalSpace.NonemptyCompacts.isometry_toCompacts EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt TopologicalSpace.NonemptyCompacts.lipschitz_sup EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt edist_ne_top_of_mem_ball EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt nhds_eq_nhds_emetric_ball EMetricSpace => PseudoEMetricSpace by rfl, simp, aesop, exact?
#fh_home_attempt Filter.map_div_atTop_eq LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt Finset.add_sup' LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt Finset.mul_sup' LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt Finset.nsmul_sup' LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt Finset.sup'_add LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt Finset.sup'_mul LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt Finset.sup'_pow LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt Nonneg.toNonneg_lt LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt Order.not_isMin_succ LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt Set.iUnion_pi_of_monotone LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt isBoundedUnder_le_finset_sup' LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt isCoboundedUnder_le_finset_sup' LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt max_le_max_left LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt max_le_max_right LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt supIrred_iff_not_isMin LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt supPrime_iff_not_isMin LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt sup_ind LinearOrder => SemilatticeSup by rfl, simp, aesop, exact?
#fh_home_attempt AddUnits.val_lt_val Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt Finsupp.coe_lt_coe Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt Positive.coe_add Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt Set.isWF_insert Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithLower.ofLower_lt_ofLower Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithLower.toLower_lt_toLower Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithUpper.ofUpper_lt_ofUpper Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt Topology.WithUpper.toUpper_lt_toUpper Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt Units.val_lt_val Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt WithTop.isSuccPrelimit_top Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.denselyOrdered_iff Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.exists_ne_zero_and_lt Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.exp_lt_exp Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.log_lt_log Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt WithZero.lt_exp_of_log_lt Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt cmp_swap Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt covBy_irrefl Preorder => LT by rfl, simp, aesop, exact?
#fh_home_attempt AddCircle.coe_eq_zero_of_pos_iff IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.SimpleFunc.integral_mono_measure IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt MeasureTheory.SimpleFunc.integral_nonneg IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt Set.add_mem_Icc_iff_right IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_add_Ici IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_add_Iic IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_sub_Ici IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt Set.preimage_const_sub_Iic IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt Set.sub_mem_Icc_iff_right IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt abs_add' IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt abs_eq IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt abs_nnqsmul IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
#fh_home_attempt abs_nsmul IsOrderedAddMonoid => AddLeftMono by rfl, simp, aesop, exact?
