/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 4 of 13 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 400000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt IsLeast.minimal Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsLeast.mono Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsLeast.nonempty Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsLowerSet.bot_mem Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsLowerSet.lowerBounds_subset Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsUpperSet.top_mem Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsUpperSet.upperBounds_subset Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Left.nsmul_nonneg Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Left.one_le_pow_of_le Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Ordnode.insert'_eq_insertWith Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Ordnode.insert_eq_insertWith Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Right.nsmul_nonneg Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Right.one_le_pow_of_le Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Finite.bddAbove_biUnion Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.not_isMax_coe Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.not_isMin_coe Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithBot.eq_bot_iff_forall_le Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithBot.le_coe_unbotD Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithTop.coe_iSup Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithTop.coe_untopD_le Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithTop.eq_top_iff_forall_ge Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithZero.exp_le_exp Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithZero.le_coe_unzeroD Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithZero.le_exp_of_log_le Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithZero.log_le_log Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt bddAbove_insert Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt bot_mem_lowerBounds Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt div_self_le_one Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt exists_nonneg_add_of_le Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt exists_one_le_mul_of_le Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_mul_le_one Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_mul_left_le Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt inv_mul_right_le Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isCofinalFor_or_isCofinalFor_of_directedOn_union Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isGLB_congr Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isGreatest_univ_iff Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isLUB_congr Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isMax_top Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isMin_bot Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_iff_exists_add' Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_iff_exists_mul' Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_inv_mul_left Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_inv_mul_right Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_mul_inv_left Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt le_mul_inv_right Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_inv_left_le Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt mul_inv_right_le Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt nsmul_le_nsmul_add_of_sq_le_add Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt nsmul_le_nsmul_right Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt pow_le_pow_left' Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt pow_le_pow_mul_of_sq_le_mul Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt top_mem_upperBounds Preorder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt AddCircle.coe_eq_zero_of_pos_iff LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt DedekindCut.lt_iff_exists LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt DedekindCut.lt_iff_exists' LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.exists_lt_of_prod_lt' LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsLowerSet.eq_empty_or_Iic LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.exists_le_of_prod_le' LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt List.exists_lt_of_prod_lt' LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.Iic_one LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.Iic_two LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.Iio_one LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.Iio_two LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.IsSuccPrelimit.le_iff_forall_le LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.aleph0_le_cof LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.aleph0_le_cof_iff LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.lt_succ_iff_of_not_isMax LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.lt_succ_iff_of_not_isMax' LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.succ_le_succ_iff LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.succ_lt_succ_iff LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt PseudoMetric.nonneg LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Ici.isSuccLimit_coe LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Ico_succ_left_eq_Ioo LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.Ioc_pred_right_eq_Ioo LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.insert_Icc_left_eq_Icc_pred LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.insert_Icc_pred_right_eq_Icc LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.insert_Icc_right_eq_Icc_succ LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.insert_Icc_succ_left_eq_Icc LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.insert_Ico_left_eq_Ico_pred_of_not_isMin LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.insert_Ioc_right_eq_Ioc_succ_of_not_isMax LinearOrder => Preorder by norm_num, omega, positivity, order, nlinarith, grind
