/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 5 of 6 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 1000000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Nonneg.mk_nnqsmul Semifield => CommSemiring by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_nnqsmul Semifield => DivisionSemiring by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.coe_zpow Semifield => DivisionSemiring by rfl, simp, aesop, exact?, grind
#fh_home_attempt Nonneg.mk_nnqsmul Semifield => DivisionSemiring by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.op_zsmul SubNegMonoid => AddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.unop_zsmul SubNegMonoid => AddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt natCast_zsmul SubNegMonoid => AddMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.op_zsmul SubNegMonoid => NSMul by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.unop_zsmul SubNegMonoid => NSMul by rfl, simp, aesop, exact?, grind
#fh_home_attempt natCast_zsmul SubNegMonoid => NSMul by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.op_zsmul SubNegMonoid => ZSMul by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddOpposite.unop_zsmul SubNegMonoid => ZSMul by rfl, simp, aesop, exact?, grind
#fh_home_attempt natCast_zsmul SubNegMonoid => ZSMul by rfl, simp, aesop, exact?, grind
#fh_home_attempt Complex.coe_smul AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Module.isTorsionFree_int_iff_isAddTorsionFree AddCommGroup => AddCancelCommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_add AddCommGroup => AddCommMagma by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_add AddCommGroup => AddCommMagma by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.ofLp_add AddCommGroup => AddSemigroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithLp.toLp_add AddCommGroup => AddSemigroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt ofDegLex_add AddCommMonoid => AddCommMagma by rfl, simp, aesop, exact?, grind
#fh_home_attempt toDegLex_add AddCommMonoid => AddCommMagma by rfl, simp, aesop, exact?, grind
#fh_home_attempt ofDegLex_add AddCommMonoid => AddCommSemigroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt toDegLex_add AddCommMonoid => AddCommSemigroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt ofDegLex_add AddCommMonoid => AddSemigroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt toDegLex_add AddCommMonoid => AddSemigroup by rfl, simp, aesop, exact?, grind
#fh_home_attempt AddMonoid.End.zero_apply AddCommMonoid => AddZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.bot_eq_zero AddCommMonoid => AddZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_neg AddGroup => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_neg AddGroup => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.ofConv_neg AddGroup => NegZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt WithConv.toConv_neg AddGroup => NegZeroClass by rfl, simp, aesop, exact?, grind
#fh_home_attempt Codisjoint.bihimp_left BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Codisjoint.bihimp_right BooleanAlgebra => GeneralizedBooleanAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Codisjoint.bihimp_left BooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Codisjoint.bihimp_right BooleanAlgebra => GeneralizedCoheytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Codisjoint.bihimp_left BooleanAlgebra => GeneralizedHeytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Codisjoint.bihimp_right BooleanAlgebra => GeneralizedHeytingAlgebra by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.coe_normUnit CommRing => CommSemiring by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.coe_pow CommRing => CommSemiring by rfl, simp, aesop, exact?, grind
#fh_home_attempt Polynomial.coe_normUnit CommRing => Ring by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.coe_pow CommRing => Ring by rfl, simp, aesop, exact?, grind
#fh_home_attempt lt_sSup_iff CompleteLinearOrder => ConditionallyCompleteLinearOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_lt_iff CompleteLinearOrder => ConditionallyCompleteLinearOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt lt_sSup_iff CompleteLinearOrder => ConditionallyCompleteLinearOrderBot by rfl, simp, aesop, exact?, grind
#fh_home_attempt sInf_lt_iff CompleteLinearOrder => ConditionallyCompleteLinearOrderBot by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_zpow DivInvMonoid => Monoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_zpow DivInvMonoid => Monoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_zpow DivInvMonoid => NPow by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_zpow DivInvMonoid => NPow by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_zpow DivInvMonoid => ZPow by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_zpow DivInvMonoid => ZPow by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_nnratCast Field => DivisionRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_ratCast Field => DivisionRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_inf_lift GeneralizedBooleanAlgebra => Lattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_sup_lift GeneralizedBooleanAlgebra => Lattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_le_lift GeneralizedBooleanAlgebra => PartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_lt_lift GeneralizedBooleanAlgebra => PartialOrder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_le_lift GeneralizedBooleanAlgebra => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.not_comp_lt_lift GeneralizedBooleanAlgebra => Preorder by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.op_pow Monoid => NPow by rfl, simp, aesop, exact?, grind
#fh_home_attempt MulOpposite.unop_pow Monoid => NPow by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.re_natCast AddCommGroupWithOne => AddCommMonoidWithOne by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuaternionAlgebra.re_natCast AddCommGroupWithOne => AddMonoidWithOne by rfl, simp, aesop, exact?, grind
#fh_home_attempt Finsupp.bot_eq_zero AddCommMonoid => AddZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_natCast AddCommMonoidWithOne => AddMonoidWithOne by rfl, simp, aesop, exact?, grind
#fh_home_attempt Matrix.conjTranspose_zsmul AddGroup => AddCancelMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Matrix.conjTranspose_zsmul AddGroup => AddRightCancelMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt ofBoolRing_neg BooleanAlgebra => CommRing by rfl, simp, aesop, exact?, grind
#fh_home_attempt ofBoolRing_neg BooleanAlgebra => HasDistribNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt ofBoolRing_neg BooleanAlgebra => InvolutiveNeg by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.FactorSet.coe_add CommMonoidWithZero => CommMonoid by rfl, simp, aesop, exact?, grind
#fh_home_attempt Associates.FactorSet.coe_add CommMonoidWithZero => MonoidWithZero by rfl, simp, aesop, exact?, grind
#fh_home_attempt iSup_symmDiff_iSup_le CompleteBooleanAlgebra => CompleteDistribLattice by rfl, simp, aesop, exact?, grind
#fh_home_attempt iSup_symmDiff_iSup_le CompleteBooleanAlgebra => Order.Coframe by rfl, simp, aesop, exact?, grind
#fh_home_attempt iSup_symmDiff_iSup_le CompleteBooleanAlgebra => Order.Frame by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_nnratCast Field => DivisionSemiring by rfl, simp, aesop, exact?, grind
#fh_home_attempt QuadraticAlgebra.re_nnratCast Field => Semifield by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_bot GeneralizedBooleanAlgebra => OrderBot by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_inf_lift GeneralizedBooleanAlgebra => SemilatticeInf by rfl, simp, aesop, exact?, grind
#fh_home_attempt Booleanisation.lift_sup_lift GeneralizedBooleanAlgebra => SemilatticeSup by rfl, simp, aesop, exact?, grind
