/-
Copyright (c) 2026 Ferris-Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
/-!
# Attempt shard 7 of 13 — generated by `scripts/attempt-plan.py`

Every data line below is a weakening `#fh_home_refute` REFUTED: the declaration's own
proof term fails under the weaker class. That verdict never meant the statement was false.
Each line asks a tactic ladder to prove it; a PROVED line is a new theorem.

The three `fh_plant_*` lines are this shard's controls — PROVED / not proved / NO
STATEMENT in that order, or the whole shard is discarded by `score-attempts.py`.

`FerrisHoward.Atlas.Home`, not `FerrisHoward` — importing the language puts the file's top
level into FH's command grammar and the next `#`-command fails to parse.
-/

set_option maxHeartbeats 400000
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- Plant A — must read PROVED: `add_comm` is exactly an `AddCommMagma` fact. -/
theorem fh_plant_easy {R : Type} [CommRing R] (a b : R) : a + b = b + a := add_comm a b

/-- Plant B — must read `not proved`: cancellation is not an `AddCommMagma` law. -/
theorem fh_plant_hard {R : Type} [CommRing R] (a b c : R) (h : a + b = a + c) : b = c :=
  add_left_cancel h

/-- Plant C — must read NO STATEMENT: `*` has no `AddCommMagma` instance. -/
theorem fh_plant_no_statement {R : Type} [CommRing R] (a b : R) : a * b = b * a :=
  mul_comm a b

#fh_home_attempt fh_plant_easy CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_hard CommRing => AddCommMagma by rfl, simp, aesop, exact?
#fh_home_attempt fh_plant_no_statement CommRing => AddCommMagma by rfl, simp, aesop, exact?

#fh_home_attempt Set.mulIndicator_apply_le PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.mulIndicator_le PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithBot.eq_top_iff_forall_ge PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithTop.le_of_untop₀_le_untop₀ PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt WithTop.untop₀_le_untop₀ PartialOrder => LE by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.frequently_lt_of_lt_limsSup ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.frequently_lt_of_lt_limsup ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt IsMaxOn.iSup_eq ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.hittingAfter_anti ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.hittingAfter_le_of_mem ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.hittingAfter_mono ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.hittingBtwn_anti ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.hittingBtwn_eq_hittingBtwn_of_exists ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.hittingBtwn_le_of_mem ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.hittingBtwn_mono_left ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.le_hittingBtwn ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.notMem_of_lt_hittingAfter ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt csInf_lt_iff ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt essInf_eq_sSup ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt essSup_eq_sInf ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt exists_lt_of_lt_csSup ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt lt_csSup_iff ConditionallyCompleteLinearOrder => ConditionallyCompleteLattice by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt AddCircle.coe_eq_zero_of_pos_iff IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.SimpleFunc.integral_mono_measure IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MeasureTheory.SimpleFunc.integral_nonneg IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.add_mem_Icc_iff_right IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_add_Ici IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_add_Iic IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_sub_Ici IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.preimage_const_sub_Iic IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.sub_mem_Icc_iff_right IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_add' IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_eq IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_nnqsmul IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_nsmul IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_sub IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt abs_sub_le IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt zsmul_left_mono IsOrderedAddMonoid => AddLeftMono by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Filter.map_div_atTop_eq LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.add_sup' LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.mul_sup' LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.nsmul_sup' LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.sup'_add LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.sup'_mul LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Finset.sup'_pow LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Nonneg.toNonneg_lt LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Order.not_isMin_succ LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Set.iUnion_pi_of_monotone LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isBoundedUnder_le_finset_sup' LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt isCoboundedUnder_le_finset_sup' LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt supIrred_iff_not_isMin LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt supPrime_iff_not_isMin LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt sup_ind LinearOrder => SemilatticeSup by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt CommRing.Pic.subsingleton_iff CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt LinearRecurrence.solSpace_rank CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MvPolynomial.dvd_X_mul_iff CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MvPolynomial.isNilpotent_iff CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MvPolynomial.prime_C_iff CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt MvPolynomial.vars_C_mul CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.IsMonicOfDegree.aeval_add CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.Monic.mem_nonZeroDivisors CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.prime_C_iff CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Polynomial.toPowerSeries_toMvPowerSeries CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt PowerSeries.derivative.ext CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt PowerSeries.rescale_injective CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt monomial_mem_adjoin_monomial CommRing => CommSemiring by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt GenContFract.succ_nth_conv_eq_squashGCF_nth_conv Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Mathlib.Meta.NormNum.IsRat.natCeil Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Rat.cast_lt_zero Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Rat.cast_nonneg Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Rat.cast_nonpos Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Rat.cast_pos Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Rat.cast_pos_of_pos Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Subfield.bot_eq_of_charZero Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt Subfield.mem_closure_iff Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt exists_rat_lt Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt geom_sum_Ico_le_of_lt_one Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt pow_div_pow_eventuallyEq_atBot Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt pow_div_pow_eventuallyEq_atTop Field => DivisionRing by norm_num, omega, positivity, order, nlinarith, grind
#fh_home_attempt div_le_one Semifield => GroupWithZero by norm_num, omega, positivity, order, nlinarith, grind
