/-
Generated by `scripts/make-confirm-file.py` — do not edit by hand.

Each `#fh_home_refute` forces one candidate weakening and asks the kernel. CONFIRMED means
the declaration's term typechecks with the weaker hypothesis; REFUTED is inconclusive (see
`FerrisHoward/Atlas/Home.lean`). The `#guard_msgs`-free form is deliberate: this file is a
measurement, not a fixture, and pinning the verdicts would defeat its purpose.
-/
import Mathlib
import FerrisHoward.Atlas.Home

-- `FerrisHoward.Atlas.Home`, not `FerrisHoward`: importing the language puts the file's
-- top level into FH's own command grammar, and the next `#`-command fails with
-- "unexpected token '#'; expected fh_item". The tool is a Lean command and needs only the
-- module that defines it.

set_option maxHeartbeats 1000000

-- BOTH
#fh_home_refute WithBot.coe_max Max
-- BOTH
#fh_home_refute WithBot.coe_min Min
-- BOTH
#fh_home_refute WithTop.coe_max Max
-- BOTH
#fh_home_refute WithTop.coe_min Min
-- BOTH
#fh_home_refute div_le_one GroupWithZero
-- BOTH
#fh_home_refute div_lt_one GroupWithZero
-- BOTH
#fh_home_refute inf_add SemilatticeInf
-- BOTH
#fh_home_refute inf_mul SemilatticeInf
-- BOTH
#fh_home_refute inv_nonneg Preorder
-- BOTH
#fh_home_refute inv_pos Preorder
-- BOTH
#fh_home_refute max_eq_left_iff SemilatticeSup
-- BOTH
#fh_home_refute max_eq_right_iff SemilatticeSup
-- BOTH
#fh_home_refute max_le_iff SemilatticeSup
-- BOTH
#fh_home_refute max_max_max_comm SemilatticeSup
-- BOTH
#fh_home_refute max_min_distrib_left DistribLattice
-- BOTH
#fh_home_refute max_min_distrib_right DistribLattice
-- BOTH
#fh_home_refute min_eq_left_iff SemilatticeInf
-- BOTH
#fh_home_refute min_eq_right_iff SemilatticeInf
-- BOTH
#fh_home_refute min_le_min_left SemilatticeInf
-- BOTH
#fh_home_refute min_le_min_right SemilatticeInf
-- BOTH
#fh_home_refute min_lt_max Lattice
-- BOTH
#fh_home_refute min_max_distrib_left DistribLattice
-- BOTH
#fh_home_refute min_max_distrib_right DistribLattice
-- BOTH
#fh_home_refute min_min_min_comm SemilatticeInf
-- BOTH
#fh_home_refute one_le_div GroupWithZero
-- BOTH
#fh_home_refute one_lt_div GroupWithZero
-- BOTH
#fh_home_refute sup_add SemilatticeSup
-- BOTH
#fh_home_refute sup_mul SemilatticeSup
-- L_ONLY
#fh_home_refute abs_two Lattice
-- L_ONLY
#fh_home_refute isLeftRegular_ofColex Mul
-- L_ONLY
#fh_home_refute List.step_iterM_nil Pure
-- L_ONLY
#fh_home_refute mabs_le_max_mabs_mabs Lattice
-- L_ONLY
#fh_home_refute mul_self_lt_mul_self Preorder
-- L_ONLY
#fh_home_refute mul_self_lt_mul_self_iff MonoidWithZero
-- L_ONLY
#fh_home_refute WithBot.lt_zero_iff_eq_bot AddZeroClass
-- L_ONLY
#fh_home_refute pow_eq_one_iff_cases PartialOrder
-- L_ONLY
#fh_home_refute mem_upperBounds LE
-- L_ONLY
#fh_home_refute neg_of_div_neg_left PosMulReflectLT
-- L_ONLY
#fh_home_refute AddOpposite.op_zsmul SMul
-- L_ONLY
#fh_home_refute Set.Iic_sdiff_right Preorder
-- L_ONLY
#fh_home_refute Codisjoint.bihimp_left DistribLattice
-- L_ONLY
#fh_home_refute lt_mul_left Preorder
-- L_ONLY
#fh_home_refute WithBot.bot_ne_natCast NatCast
-- L_ONLY
#fh_home_refute StateT.run_pure Pure
-- L_ONLY
#fh_home_refute add_eq_right AddZeroClass
-- L_ONLY
#fh_home_refute WithTop.natCast_ne_top NatCast
-- L_ONLY
#fh_home_refute abs_sub_le Lattice
-- L_ONLY
#fh_home_refute isRightRegular_toDual Mul
-- L_ONLY
#fh_home_refute add_inf SemilatticeInf
-- L_ONLY
#fh_home_refute strictMono_div_right_of_pos GroupWithZero
-- L_ONLY
#fh_home_refute MulOpposite.unop_eq_zero_iff OfNat
-- L_ONLY
#fh_home_refute nsmul_eq_smul NSMul
-- L_ONLY
#fh_home_refute Units.inv_pos PartialOrder
-- L_ONLY
#fh_home_refute lowerBounds_union LE
-- L_ONLY
#fh_home_refute Additive.ofMul_le LE
-- L_ONLY
#fh_home_refute inv_neg'' Preorder
-- L_ONLY
#fh_home_refute isAddLeftRegular_toLex Add
-- L_ONLY
#fh_home_refute exists_square_le Preorder
-- L_ONLY
#fh_home_refute upperBounds_mono_set LE
-- L_ONLY
#fh_home_refute Disjoint.le_symmDiff_sup_symmDiff_left GeneralizedCoheytingAlgebra
-- L_ONLY
#fh_home_refute WithZero.log_le_log LE
-- L_ONLY
#fh_home_refute bihimp_le_iff_left GeneralizedBooleanAlgebra
-- L_ONLY
#fh_home_refute Set.Icc_self Preorder
-- L_ONLY
#fh_home_refute mabs_le Lattice
-- L_ONLY
#fh_home_refute WithZero.lt_exp_of_log_lt LT
-- L_ONLY
#fh_home_refute Multiplicative.toAdd_lt LT
-- L_ONLY
#fh_home_refute Array.step_iterM Pure
-- L_ONLY
#fh_home_refute isRightRegular_toLex Mul
-- L_ONLY
#fh_home_refute WithTop.coe_lt_one OfNat
-- L_ONLY
#fh_home_refute WithBot.coe_inf Min
-- L_ONLY
#fh_home_refute Set.Nonempty.eq_zero OfNat
-- L_ONLY
#fh_home_refute mabs_le_mabs_of_le_one Lattice
-- L_ONLY
#fh_home_refute WithBot.coe_nonneg OfNat
-- L_ONLY
#fh_home_refute Std.Iterators.ULiftT.run_pure Pure
-- L_ONLY
#fh_home_refute pow_pos Preorder
-- L_ONLY
#fh_home_refute npowRec'_mul_comm Mul
-- L_ONLY
#fh_home_refute IsLUB.dual LE
-- L_ONLY
#fh_home_refute Subtype.mk_sup_mk Max
-- L_ONLY
#fh_home_refute WithTop.coe_sup Max
-- L_ONLY
#fh_home_refute Mathlib.Meta.Positivity.div_ne_zero_of_ne_zero_of_pos Preorder
-- L_ONLY
#fh_home_refute sup_bihimp_bihimp GeneralizedCoheytingAlgebra
-- L_ONLY
#fh_home_refute lt_of_mabs_lt Lattice
-- L_ONLY
#fh_home_refute div_le_iff₀' MulPosReflectLT
-- L_ONLY
#fh_home_refute inf_sub SemilatticeInf
-- L_ONLY
#fh_home_refute bihimp_himp_left GeneralizedBooleanAlgebra
-- L_ONLY
#fh_home_refute WithBot.bot_ne_one OfNat
-- L_ONLY
#fh_home_refute AddOpposite.unop_eq_zero_iff OfNat
-- L_ONLY
#fh_home_refute MulEquiv.coe_monoidHom_refl MulOne
-- L_ONLY
#fh_home_refute uniform_continuous_npow_on_bounded IsOrderedRing
-- L_ONLY
#fh_home_refute Lean.Grind.CommRing.Poly.normEq0_eq Lean.Grind.Ring
-- L_ONLY
#fh_home_refute himp_bihimp_eq_inf GeneralizedCoheytingAlgebra
-- L_ONLY
#fh_home_refute WithZero.le_coe_unzeroD LE
-- L_ONLY
#fh_home_refute isAddLeftRegular_toAdd Add
-- L_ONLY
#fh_home_refute WithTop.exists_le_coe LE
-- L_ONLY
#fh_home_refute Int.cast_le_neg_one_of_neg PartialOrder
-- L_ONLY
#fh_home_refute WithTop.natCast_lt_top NatCast
-- L_ONLY
#fh_home_refute IsGLB.bddBelow LE
-- L_ONLY
#fh_home_refute toColex_one OfNat
-- L_ONLY
#fh_home_refute codisjoint_iff_compl_le_left CoheytingAlgebra
-- L_ONLY
#fh_home_refute MulOpposite.op_eq_zero_iff OfNat
-- L_ONLY
#fh_home_refute WithBot.coe_lt_zero OfNat
-- L_ONLY
#fh_home_refute WithTop.coe_one OfNat
-- L_ONLY
#fh_home_refute Subtype.coe_inf Min
-- L_ONLY
#fh_home_refute isAddLeftRegular_toColex Add
-- L_ONLY
#fh_home_refute WithBot.one_eq_map_iff OfNat
-- L_ONLY
#fh_home_refute symmDiff_symmDiff_cancel_left GeneralizedCoheytingAlgebra
-- L_ONLY
#fh_home_refute WithTop.top_ne_one OfNat
-- L_ONLY
#fh_home_refute Vector.smul_zero OfNat
-- L_ONLY
#fh_home_refute Int.cast_one_le_of_pos PartialOrder
-- L_ONLY
#fh_home_refute isRightRegular_ofDual Mul
-- L_ONLY
#fh_home_refute nsmul_le_nsmul_right LE
-- L_ONLY
#fh_home_refute isMax_top LE
-- L_ONLY
#fh_home_refute inf_himp_bihimp GeneralizedBooleanAlgebra
-- L_ONLY
#fh_home_refute min_mul_of_nonneg MonoidWithZero
-- L_ONLY
#fh_home_refute mabs_mul_three Lattice
-- L_ONLY
#fh_home_refute max_div_div_right PosMulReflectLT
-- L_ONLY
#fh_home_refute Std.Iterators.Vector.isPlausibleStep_iterFromIdxM_of_lt Pure
-- L_ONLY
#fh_home_refute minimal_iff_isLeast Preorder
-- L_ONLY
#fh_home_refute one_lt_mul_iff Monoid
-- L_ONLY
#fh_home_refute isLeftRegular_toMul Mul
-- L_ONLY
#fh_home_refute List.le_total Std.Total
-- L_ONLY
#fh_home_refute nonpos_of_mul_nonpos_left MulZeroClass
-- L_ONLY
#fh_home_refute pow_eq_pow_iff_cases PartialOrder
-- L_ONLY
#fh_home_refute isGreatest_univ_iff LE
-- L_ONLY
#fh_home_refute inv_le_inv' Preorder
-- L_ONLY
#fh_home_refute bot_eq_zero' AddZeroClass
-- L_ONLY
#fh_home_refute WithZero.exp_lt_exp LT
-- L_ONLY
#fh_home_refute posMulStrictMono_iff_posMulReflectLE Preorder
-- L_ONLY
#fh_home_refute symmDiff_left_comm GeneralizedCoheytingAlgebra
-- L_ONLY
#fh_home_refute nsmul_iterate SMul
-- L_ONLY
#fh_home_refute bihimp_left_surjective GeneralizedBooleanAlgebra
-- L_ONLY
#fh_home_refute WithTop.zero_ne_top OfNat
-- L_ONLY
#fh_home_refute bddBelow_preimage_ofDual LE
-- L_ONLY
#fh_home_refute le_min_iff SemilatticeInf
-- L_ONLY
#fh_home_refute Mathlib.Meta.Positivity.div_ne_zero_of_pos_of_ne_zero Preorder
-- L_ONLY
#fh_home_refute IsRightRegular.mul_right_eq_self_iff MulOneClass
-- L_ONLY
#fh_home_refute subset_lowerBounds_upperBounds LE
-- L_ONLY
#fh_home_refute WithTop.coe_nonneg OfNat
-- L_ONLY
#fh_home_refute isAddLeftRegular_ofMul Mul
-- L_ONLY
#fh_home_refute WithTop.one_lt_coe OfNat
-- L_ONLY
#fh_home_refute isAddRightRegular_toDual Add
-- L_ONLY
#fh_home_refute min_le_of_left_le SemilatticeInf
-- L_ONLY
#fh_home_refute lt_isLUB_iff Preorder
-- L_ONLY
#fh_home_refute even_iff_exists_two_mul NonAssocSemiring
-- L_ONLY
#fh_home_refute MulOpposite.unop_eq_one_iff OfNat
-- L_ONLY
#fh_home_refute WithTop.coe_lt_zero OfNat
-- L_ONLY
#fh_home_refute bihimp_left_injective GeneralizedBooleanAlgebra
-- L_ONLY
#fh_home_refute nsmul_le_nsmul_add_of_sq_le_add LE
-- S_ONLY
#fh_home_refute min_left_comm SemilatticeInf
-- S_ONLY
#fh_home_refute IsStrictOrderedRing.toZeroLEOneClass IsOrderedRing
-- S_ONLY
#fh_home_refute mul_lt_mul_of_nonneg MulPosStrictMono
-- S_ONLY
#fh_home_refute NonUnitalNonAssocRing.right_distrib Distrib
-- S_ONLY
#fh_home_refute DivisionRing.zpow_succ' DivInvMonoid
-- S_ONLY
#fh_home_refute AddMonoid.zero_add AddZeroClass
-- S_ONLY
#fh_home_refute eq_one_of_mul_right' LeftCancelMonoid
-- S_ONLY
#fh_home_refute CommRing.mul_comm CommMagma
-- S_ONLY
#fh_home_refute max_comm SemilatticeSup
-- S_ONLY
#fh_home_refute max_bot_right SemilatticeSup
-- S_ONLY
#fh_home_refute Std.IsLinearPreorder.toIsPreorder Std.IsPreorder
-- S_ONLY
#fh_home_refute BiheytingAlgebra.sdiff_le_iff GeneralizedCoheytingAlgebra
-- S_ONLY
#fh_home_refute AddGroupWithOne.zsmul_zero' SubNegMonoid
-- S_ONLY
#fh_home_refute AddCommGroupWithOne.intCast_negSucc AddGroupWithOne
-- S_ONLY
#fh_home_refute Std.IsPartialOrder.toIsPreorder Std.IsPreorder
-- S_ONLY
#fh_home_refute MulZeroOneClass.mul_zero MulZeroClass
-- S_ONLY
#fh_home_refute LinearOrderedCommGroupWithZero.mul_inv_cancel CommGroupWithZero
-- S_ONLY
#fh_home_refute min_top_right SemilatticeInf
-- S_ONLY
#fh_home_refute Field.nnratCast_def DivisionRing
-- S_ONLY
#fh_home_refute LinearOrderedAddCommGroupWithTop.zsmul_neg' SubNegMonoid
-- S_ONLY
#fh_home_refute DivisionSemiring.zpow_neg' DivInvMonoid
-- S_ONLY
#fh_home_refute eq_zero_of_add_left' AddLeftCancelMonoid
-- S_ONLY
#fh_home_refute AddCommGroupWithOne.natCast_succ AddMonoidWithOne
-- S_ONLY
#fh_home_refute Ring.zsmul_succ' AddGroupWithOne
-- S_ONLY
#fh_home_refute GroupWithZero.zpow_neg' DivInvMonoid
-- S_ONLY
#fh_home_refute Semifield.mul_inv_cancel CommGroupWithZero
-- S_ONLY
#fh_home_refute LinearOrderedAddCommGroupWithTop.sub_eq_add_neg SubNegMonoid
-- S_ONLY
#fh_home_refute LinearOrderedAddCommGroupWithTop.zsmul_zero' SubNegMonoid
-- S_ONLY
#fh_home_refute RightCancelMonoid.toIsRightCancelMul RightCancelSemigroup
-- S_ONLY
#fh_home_refute Field.ratCast_def DivisionRing
-- S_ONLY
#fh_home_refute NonUnitalNonAssocRing.mul_zero MulZeroClass
-- S_ONLY
#fh_home_refute AddMonoid.add_zero AddZeroClass
-- S_ONLY
#fh_home_refute Field.inv_zero CommGroupWithZero
-- S_ONLY
#fh_home_refute Semiring.natCast_zero AddMonoidWithOne
-- S_ONLY
#fh_home_refute min_assoc SemilatticeInf
-- S_ONLY
#fh_home_refute DivisionSemiring.toNontrivial GroupWithZero
-- S_ONLY
#fh_home_refute Field.isDomain DivisionRing
-- S_ONLY
#fh_home_refute Lean.Grind.Semiring.add_assoc Lean.Grind.AddCommMonoid
-- S_ONLY
#fh_home_refute SemigroupWithZero.mul_zero MulZeroClass
-- S_ONLY
#fh_home_refute instLawfulOrderLT_mathlib LE
-- S_ONLY
#fh_home_refute NonAssocCommRing.mul_comm CommMagma
-- S_ONLY
#fh_home_refute Lean.Grind.Semiring.add_comm Lean.Grind.AddCommMonoid
-- S_ONLY
#fh_home_refute Ring.zsmul_zero' AddGroupWithOne
-- S_ONLY
#fh_home_refute IsDomain.to_noZeroDivisors IsLeftCancelMulZero
-- S_ONLY
#fh_home_refute neg_of_mul_neg_right MulPosMono
-- S_ONLY
#fh_home_refute Int.cast_pow Lean.Grind.Ring
-- S_ONLY
#fh_home_refute BiheytingAlgebra.top_sdiff CoheytingAlgebra
-- S_ONLY
#fh_home_refute Semifield.toNontrivial CommGroupWithZero
-- S_ONLY
#fh_home_refute AddCommGroupWithOne.intCast_ofNat AddGroupWithOne
-- S_ONLY
#fh_home_refute CommGroupWithZero.toNontrivial GroupWithZero
-- S_ONLY
#fh_home_refute AddGroupWithOne.neg_add_cancel AddGroup
-- S_ONLY
#fh_home_refute Std.IsLinearOrder.le_total Std.IsLinearPreorder
-- S_ONLY
#fh_home_refute NonUnitalNonAssocSemiring.right_distrib Distrib
-- S_ONLY
#fh_home_refute sup_inf_left LinearOrder
-- S_ONLY
#fh_home_refute Field.mul_inv_cancel CommGroupWithZero
-- S_ONLY
#fh_home_refute abs_abs_sub_abs_le_abs_sub AddLeftMono
-- S_ONLY
#fh_home_refute CommMonoidWithZero.zero_mul MonoidWithZero
-- S_ONLY
#fh_home_refute IsOrderedAddMonoid.toIsOrderedCancelAddMonoid AddCancelCommMonoid
-- S_ONLY
#fh_home_refute DivisionRing.inv_zero DivisionSemiring
-- S_ONLY
#fh_home_refute LinearOrderedCommGroupWithZero.zpow_zero' CommGroupWithZero
-- S_ONLY
#fh_home_refute Left.neg_of_mul_neg_left MulPosMono
-- S_ONLY
#fh_home_refute AddGroupWithOne.zsmul_neg' SubNegMonoid
-- S_ONLY
#fh_home_refute LinearOrderedAddCommGroupWithTop.zsmul_succ' SubNegMonoid
-- S_ONLY
#fh_home_refute MonoidHom.instMonoidHomClassMulHom_2 LeftCancelMonoid
-- S_ONLY
#fh_home_refute GroupWithZero.div_eq_mul_inv DivInvMonoid
-- S_ONLY
#fh_home_refute Ring.sub_eq_add_neg AddGroupWithOne
-- S_ONLY
#fh_home_refute SubtractionCommMonoid.add_comm AddCommMagma
-- S_ONLY
#fh_home_refute CancelMonoid.toIsRightCancelMul RightCancelMonoid
-- S_ONLY
#fh_home_refute Field.zpow_neg' CommGroupWithZero
-- S_ONLY
#fh_home_refute IsOrderedMonoid.toIsOrderedCancelMonoid CancelCommMonoid
-- S_ONLY
#fh_home_refute NonUnitalNonAssocRing.zero_mul MulZeroClass
-- S_ONLY
#fh_home_refute max_le SemilatticeSup
-- S_ONLY
#fh_home_refute DivisionSemiring.div_eq_mul_inv DivInvMonoid
-- S_ONLY
#fh_home_refute Semifield.nnratCast_def DivisionSemiring
-- S_ONLY
#fh_home_refute NonUnitalNonAssocCommSemiring.mul_comm CommMagma
-- S_ONLY
#fh_home_refute Lean.Grind.CommRing.OfCommSemiring.instAssociativeHMul Lean.Grind.Semiring
-- S_ONLY
#fh_home_refute Field.zpow_succ' CommGroupWithZero
-- S_ONLY
#fh_home_refute max_top_right SemilatticeSup
-- S_ONLY
#fh_home_refute IsOrderedRing.toZeroLEOneClass IsStrictOrderedRing
-- S_ONLY
#fh_home_refute add_ne_zero' AddLeftCancelMonoid
-- S_ONLY
#fh_home_refute Left.mul_lt_mul_of_nonneg MulPosStrictMono
-- S_ONLY
#fh_home_refute NonAssocRing.one_mul MulOneClass
-- S_ONLY
#fh_home_refute NonAssocSemiring.one_mul MulOneClass
-- S_ONLY
#fh_home_refute Lean.Grind.LinearOrder.lt_of_not_le Std.IsLinearPreorder
-- S_ONLY
#fh_home_refute min_self SemilatticeInf
-- S_ONLY
#fh_home_refute DivInvOneMonoid.inv_one InvOneClass
-- S_ONLY
#fh_home_refute mabs_mabs_div_mabs_le_mabs_div Lattice
-- S_ONLY
#fh_home_refute CommGroupWithZero.inv_zero GroupWithZero
-- S_ONLY
#fh_home_refute Lean.Grind.Semiring.add_zero Lean.Grind.AddCommMonoid
-- S_ONLY
#fh_home_refute Semifield.zpow_zero' CommGroupWithZero
-- S_ONLY
#fh_home_refute NonUnitalNonAssocCommRing.mul_comm CommMagma
-- S_ONLY
#fh_home_refute inf_lt_sup LinearOrder
-- S_ONLY
#fh_home_refute Lean.Grind.Ring.sub_eq_add_neg Lean.Grind.AddCommGroup
-- S_ONLY
#fh_home_refute AddCancelMonoid.toIsRightCancelAdd AddRightCancelMonoid
-- S_ONLY
#fh_home_refute ofDual_max Min
-- S_ONLY
#fh_home_refute mul_ne_one' LeftCancelMonoid
-- S_ONLY
#fh_home_refute Semifield.inv_zero CommGroupWithZero
-- S_ONLY
#fh_home_refute min_eq_left SemilatticeInf
-- S_ONLY
#fh_home_refute Eq.subset' LE
-- S_ONLY
#fh_home_refute max_self SemilatticeSup
-- S_ONLY
#fh_home_refute top_sdiff' BiheytingAlgebra
-- S_ONLY
#fh_home_refute Lean.Grind.Order.le_of_eq_1 Std.Refl
-- S_ONLY
#fh_home_refute NonUnitalNonAssocSemiring.left_distrib Distrib
-- S_ONLY
#fh_home_refute DivisionRing.mul_inv_cancel DivisionSemiring
-- S_ONLY
#fh_home_refute min_bot_right SemilatticeInf
-- S_ONLY
#fh_home_refute max_bot_left SemilatticeSup
-- S_ONLY
#fh_home_refute Semiring.mul_zero Lean.Grind.Semiring
-- S_ONLY
#fh_home_refute AddRightCancelMonoid.toIsRightCancelAdd AddRightCancelSemigroup
-- S_ONLY
#fh_home_refute inf_sup_right LinearOrder
-- S_ONLY
#fh_home_refute NonUnitalSemiring.mul_assoc Semigroup
-- S_ONLY
#fh_home_refute ofDual_min Max
-- S_ONLY
#fh_home_refute LinearOrderedCommGroupWithZero.div_eq_mul_inv CommGroupWithZero
-- S_ONLY
#fh_home_refute add_eq_zero' AddLeftCancelMonoid
-- S_ONLY
#fh_home_refute toDual_min Min
-- S_ONLY
#fh_home_refute SemigroupWithZero.zero_mul MulZeroClass
-- S_ONLY
#fh_home_refute AddLeftCancelMonoid.toIsLeftCancelAdd AddLeftCancelSemigroup
-- S_ONLY
#fh_home_refute Lean.Grind.Ring.neg_zsmul Lean.Grind.IntModule
-- S_ONLY
#fh_home_refute CoheytingAlgebra.top_sdiff BiheytingAlgebra
-- S_ONLY
#fh_home_refute AddMonoidHom.instAddMonoidHomClassAddHom_2 AddLeftCancelMonoid
-- S_ONLY
#fh_home_refute SubtractionMonoid.neg_neg InvolutiveNeg
