/-
Copyright (c) 2026 Ferris–Howard contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Crystal.Wallpaper.Groups.Pm

/-!
# W1, fourth witness — pg, the glide group

`Pg` is generated by the glide `x ↦ reflect x + glideVec` (mirror in the horizontal
axis, then a *half*-unit step along it) and the vertical unit translation.  The carrier
is again given in closed form so membership carries its vector, but here the two element
forms carry *different* vector sets:

* translation-form elements carry `stdLattice` — the glide squares to the horizontal
  unit translation (`reflect` fixes `glideVec`, so the half-steps add to `stdVec 0`),
  which together with `stdVec 1` spans the full rank-2 lattice; and
* glide-form elements carry the *coset* `glideVec + stdLattice` — odd half-integer
  first coordinate — which is what keeps every mirror-form element off the lattice.

pg is the census's first non-symmorphic group: no choice of origin turns it into a
point group extended by translations.  That is W4 material (vector systems mod
coboundaries); W1 needs only existence, so nothing here states it.
-/

namespace Crystal.Wallpaper

/-- The glide vector: half a unit along the mirror axis. -/
noncomputable def glideVec : Plane := (2⁻¹ : ℝ) • stdVec 0

/-- The vectors carried by glide-form elements: the coset `glideVec + stdLattice`,
stated as a membership predicate so closure proofs are lattice arithmetic. -/
def pgGlideVecs : Set Plane := {v | v - glideVec ∈ stdLattice}

theorem mem_pgGlideVecs {v : Plane} : v ∈ pgGlideVecs ↔ v - glideVec ∈ stdLattice :=
  Iff.rfl

theorem glideVec_mem_pgGlideVecs : glideVec ∈ pgGlideVecs := by
  rw [mem_pgGlideVecs, sub_self]
  exact zero_mem _

/-- The glide vector lies along the mirror axis, so the mirror fixes it. -/
theorem reflect_glideVec : reflect glideVec = glideVec := by
  rw [glideVec, reflect_smul, reflect_stdVec_zero]

/-- Two half-steps make the horizontal unit translation — why the glide's square is a
lattice translation, and why pg's translations still span rank 2. -/
theorem glideVec_add_glideVec : glideVec + glideVec = stdVec 0 := by
  rw [glideVec, ← add_smul]
  norm_num

/-- **pg**: translations by lattice vectors together with glide-form maps
`x ↦ reflect x + v`, `v` in the *half-shifted* coset. -/
def Pg : Subgroup E2 where
  carrier := {h | ∃ v, IsTranslationBy h v ∧ v ∈ stdLattice ∨
    (∀ x, h x = reflect x + v) ∧ v ∈ pgGlideVecs}
  one_mem' := ⟨0, Or.inl ⟨fun x => (add_zero x).symm, zero_mem _⟩⟩
  mul_mem' := by
    rintro a b ⟨v, ⟨hav, hv⟩ | ⟨hav, hv⟩⟩ ⟨w, ⟨hbw, hw⟩ | ⟨hbw, hw⟩⟩
    · exact ⟨w + v, Or.inl ⟨hav.mul hbw, add_mem hw hv⟩⟩
    · -- translation ∘ glide-form: the coset absorbs lattice vectors.
      refine ⟨w + v, Or.inr ⟨fun x => ?_, ?_⟩⟩
      · calc (a * b) x = a (b x) := rfl
          _ = (reflect x + w) + v := by rw [hbw x, hav (reflect x + w)]
          _ = reflect x + (w + v) := add_assoc _ _ _
      · rw [mem_pgGlideVecs, ← sub_add_eq_add_sub]
        exact add_mem hw hv
    · -- glide-form ∘ translation: the lattice vector enters mirrored, staying in the
      -- lattice, so the sum stays in the coset.
      refine ⟨reflect w + v, Or.inr ⟨fun x => ?_, ?_⟩⟩
      · calc (a * b) x = a (b x) := rfl
          _ = reflect (x + w) + v := by rw [hbw x, hav (x + w)]
          _ = reflect x + (reflect w + v) := by rw [reflect_add, add_assoc]
      · rw [mem_pgGlideVecs, add_sub_assoc]
        exact add_mem (reflect_mem_stdLattice hw) hv
    · -- glide-form ∘ glide-form: a translation, and the two half-steps combine into
      -- the horizontal unit — the resulting vector is genuinely in the lattice.
      refine ⟨reflect w + v, Or.inl ⟨fun x => ?_, ?_⟩⟩
      · calc (a * b) x = a (b x) := rfl
          _ = reflect (reflect x + w) + v := by rw [hbw x, hav (reflect x + w)]
          _ = x + (reflect w + v) := by rw [reflect_add, reflect_reflect, add_assoc]
      · have hsplit : reflect w + v =
            reflect (w - glideVec) + (v - glideVec) + stdVec 0 := by
          rw [reflect_sub, reflect_glideVec, ← glideVec_add_glideVec]
          abel
        rw [hsplit]
        exact add_mem (add_mem (reflect_mem_stdLattice hw) hv) stdVec_zero_mem_stdLattice
  inv_mem' := by
    rintro a ⟨v, ⟨hav, hv⟩ | ⟨hav, hv⟩⟩
    · exact ⟨-v, Or.inl ⟨hav.inv, neg_mem hv⟩⟩
    · -- the inverse of x ↦ reflect x + v is x ↦ reflect x + (-reflect v), and negating
      -- a coset vector lands back in the coset because the mirrored half-steps cancel
      -- against a full unit.
      refine ⟨-reflect v, Or.inr ⟨fun x =>
        inv_apply_eq (f := fun y => reflect y + -reflect v) (fun y => ?_) x, ?_⟩⟩
      · rw [hav (reflect y + -reflect v), reflect_add, reflect_reflect, reflect_neg,
          reflect_reflect]
        abel
      · have hsplit : -reflect v - glideVec = -reflect (v - glideVec) - stdVec 0 := by
          rw [reflect_sub, reflect_glideVec, ← glideVec_add_glideVec]
          abel
        rw [mem_pgGlideVecs, hsplit]
        exact sub_mem (neg_mem (reflect_mem_stdLattice hv)) stdVec_zero_mem_stdLattice

theorem mem_Pg {g : E2} :
    g ∈ Pg ↔ ∃ v, IsTranslationBy g v ∧ v ∈ stdLattice ∨
      (∀ x, g x = reflect x + v) ∧ v ∈ pgGlideVecs := Iff.rfl

/-- The glides contribute no translation vectors — a glide-form element is never a
translation, whatever its vector — so `transVecs Pg` is the full lattice and pg has
rank-2 translations like every wallpaper group. -/
theorem transVecs_Pg : transVecs Pg = (stdLattice : Set Plane) := by
  refine Set.Subset.antisymm ?_ (stdLattice_subset_transVecs fun v hv =>
    mem_Pg.mpr ⟨v, Or.inl ⟨isTranslationBy_translationIso v, hv⟩⟩)
  rintro u ⟨g, hgPg, hgu⟩
  obtain ⟨v, ⟨hgv, hv⟩ | ⟨hgv, -⟩⟩ := mem_Pg.mp hgPg
  · rwa [hgu.unique hgv]
  · exact (reflect_form_not_isTranslationBy hgv hgu).elim

/-- The glide itself: mirror, then half a unit along the axis. -/
noncomputable def glide₀ : E2 := translationIso glideVec * reflect

theorem glide₀_apply (x : Plane) : glide₀ x = reflect x + glideVec := rfl

/-- **pg is a wallpaper group** — the coset condition holds with `{1, glide₀}`:
composing a glide-form element with the glide's inverse recovers a translation (by a
*half-integer* vector, which `IsTranslation` is indifferent to). -/
theorem pg_isWallpaperGroup : IsWallpaperGroup Pg := by
  classical
  refine ⟨⟨stdVec 0, stdVec 1, linearIndependent_stdVec, transVecs_Pg⟩,
    {1, glide₀}, ?_, ?_⟩
  · intro g hg
    simp only [Finset.coe_insert, Set.mem_insert_iff, Finset.coe_singleton,
      Set.mem_singleton_iff] at hg
    rcases hg with rfl | rfl
    · exact one_mem Pg
    · exact mem_Pg.mpr ⟨glideVec, Or.inr ⟨glide₀_apply, glideVec_mem_pgGlideVecs⟩⟩
  · intro g hg
    obtain ⟨v, ⟨hgv, -⟩ | ⟨hgv, -⟩⟩ := mem_Pg.mp hg
    · exact ⟨1, Finset.mem_insert_self 1 _, by rw [inv_one, mul_one]; exact ⟨v, hgv⟩⟩
    · refine ⟨glide₀, Finset.mem_insert_of_mem (Finset.mem_singleton_self _),
        v - glideVec, fun x => ?_⟩
      have hinv : glide₀⁻¹ x = reflect x + -glideVec :=
        inv_apply_eq (f := fun y => reflect y + -glideVec) (fun y => by
          rw [glide₀_apply (reflect y + -glideVec), reflect_add, reflect_reflect,
            reflect_neg, reflect_glideVec]
          abel) x
      calc (g * glide₀⁻¹) x = g (glide₀⁻¹ x) := rfl
        _ = g (reflect x + -glideVec) := by rw [hinv]
        _ = reflect (reflect x + -glideVec) + v := hgv _
        _ = x + (v - glideVec) := by
            rw [reflect_add, reflect_reflect, reflect_neg, reflect_glideVec]
            abel

end Crystal.Wallpaper
